//go:build integration

package league

import (
	"encoding/json"
	"fmt"
	"net/http"
	"slices"
	"strings"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"league-s/internal/db"
	"league-s/internal/testdb"
	"league-s/internal/testhttp"
)

func newTestRouter() http.Handler {
	r := chi.NewRouter()
	r.Mount("/api/v1/leagues", NewHandler(NewPostgresStore(testPool)).Routes())
	return r
}

func leaguePath(l db.League) string {
	return fmt.Sprintf("/api/v1/leagues/%s", l.ID)
}

func TestCreateThenGetLeague(t *testing.T) {
	tests := []struct {
		name     string
		body     string
		wantLogo *string
	}{
		{
			name:     "with logo",
			body:     `{"name": "Ligue 1", "logo": "https://example.com/l1.png"}`,
			wantLogo: new("https://example.com/l1.png"),
		},
		{
			name:     "without logo",
			body:     `{"name": "Ligue 1"}`,
			wantLogo: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			testdb.New(t, testPool)
			router := newTestRouter()

			rec := testhttp.Do(t, router, http.MethodPost, "/api/v1/leagues", tt.body)
			if rec.Code != http.StatusCreated {
				t.Fatalf("create: status = %d, want %d, body = %s", rec.Code, http.StatusCreated, rec.Body)
			}

			var created leagueResponse
			if err := json.NewDecoder(rec.Body).Decode(&created); err != nil {
				t.Fatalf("decode create response: %v", err)
			}
			if created.ID == uuid.Nil {
				t.Fatal("create: id is 0, want the id generated by the database")
			}

			rec = testhttp.Do(t, router, http.MethodGet, fmt.Sprintf("/api/v1/leagues/%s", created.ID), "")
			if rec.Code != http.StatusOK {
				t.Fatalf("get: status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
			}

			var got leagueResponse
			if err := json.NewDecoder(rec.Body).Decode(&got); err != nil {
				t.Fatalf("decode get response: %v", err)
			}
			if got.Name != "Ligue 1" {
				t.Errorf("get: name = %q, want %q", got.Name, "Ligue 1")
			}
			if !equalPtr(got.Logo, tt.wantLogo) {
				t.Errorf("get: logo = %v, want %v", deref(got.Logo), deref(tt.wantLogo))
			}
		})
	}
}

func TestCreateLeague_Errors(t *testing.T) {
	tests := []struct {
		name       string
		body       string
		wantStatus int
	}{
		{"invalid JSON", `{"name":`, http.StatusBadRequest},
		{"missing name", `{}`, http.StatusUnprocessableEntity},
		{"name too long", `{"name": "` + strings.Repeat("a", 51) + `"}`, http.StatusUnprocessableEntity},
		{"logo is not a URL", `{"name": "Ligue 1", "logo": "not a url"}`, http.StatusUnprocessableEntity},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			testdb.New(t, testPool)
			rec := testhttp.Do(t, newTestRouter(), http.MethodPost, "/api/v1/leagues", tt.body)
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func TestGetLeague_Errors(t *testing.T) {
	tests := []struct {
		name       string
		path       string
		wantStatus int
	}{
		{"unknown id", "/api/v1/leagues/" + uuid.NewString(), http.StatusNotFound},
		{"invalid id", "/api/v1/leagues/abc", http.StatusBadRequest},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			testdb.New(t, testPool)
			rec := testhttp.Do(t, newTestRouter(), http.MethodGet, tt.path, "")
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func TestListLeagues(t *testing.T) {
	tests := []struct {
		name      string
		seed      []string
		wantNames []string
	}{
		{"sorted by name", []string{"Urban B", "Five A"}, []string{"Five A", "Urban B"}},
		{"no league", nil, []string{}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := testdb.New(t, testPool)
			for _, name := range tt.seed {
				s.CreateLeague(testdb.LeagueParams{Name: name})
			}

			rec := testhttp.Do(t, newTestRouter(), http.MethodGet, "/api/v1/leagues", "")
			if rec.Code != http.StatusOK {
				t.Fatalf("status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
			}

			var got []leagueResponse
			if err := json.NewDecoder(rec.Body).Decode(&got); err != nil {
				t.Fatalf("decode response: %v, body = %s", err, rec.Body)
			}
			if got == nil {
				t.Fatal("body is null, want a JSON array")
			}

			names := []string{}
			for _, l := range got {
				names = append(names, l.Name)
			}
			if !slices.Equal(names, tt.wantNames) {
				t.Errorf("leagues = %v, want %v", names, tt.wantNames)
			}
		})
	}
}

func TestDeleteLeague(t *testing.T) {
	s := testdb.New(t, testPool)
	league := s.CreateLeague(testdb.LeagueParams{})
	other := s.CreateLeague(testdb.LeagueParams{})
	router := newTestRouter()

	rec := testhttp.Do(t, router, http.MethodDelete, leaguePath(league), "")
	if rec.Code != http.StatusNoContent {
		t.Fatalf("delete: status = %d, want %d, body = %s", rec.Code, http.StatusNoContent, rec.Body)
	}

	rec = testhttp.Do(t, router, http.MethodGet, leaguePath(league), "")
	if rec.Code != http.StatusNotFound {
		t.Errorf("get after delete: status = %d, want %d", rec.Code, http.StatusNotFound)
	}

	rec = testhttp.Do(t, router, http.MethodGet, leaguePath(other), "")
	if rec.Code != http.StatusOK {
		t.Errorf("other league: status = %d, want %d: only the requested league must be deleted", rec.Code, http.StatusOK)
	}
}

func TestDeleteLeague_Errors(t *testing.T) {
	tests := []struct {
		name       string
		seed       func(s *testdb.Seeder, l db.League)
		path       func(l db.League) string
		wantStatus int
	}{
		{
			name:       "unknown id",
			path:       func(db.League) string { return "/api/v1/leagues/" + uuid.NewString() },
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "invalid id",
			path:       func(db.League) string { return "/api/v1/leagues/abc" },
			wantStatus: http.StatusBadRequest,
		},
		{
			name:       "league has teams",
			seed:       func(s *testdb.Seeder, l db.League) { s.CreateTeam(testdb.TeamParams{League: &l}) },
			path:       leaguePath,
			wantStatus: http.StatusConflict,
		},
		{
			name:       "league has players",
			seed:       func(s *testdb.Seeder, l db.League) { s.CreatePlayer(testdb.PlayerParams{League: &l}) },
			path:       leaguePath,
			wantStatus: http.StatusConflict,
		},
		{
			name:       "league has seasons",
			seed:       func(s *testdb.Seeder, l db.League) { s.CreateSeason(testdb.SeasonParams{League: &l}) },
			path:       leaguePath,
			wantStatus: http.StatusConflict,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := testdb.New(t, testPool)
			league := s.CreateLeague(testdb.LeagueParams{})
			if tt.seed != nil {
				tt.seed(s, league)
			}

			rec := testhttp.Do(t, newTestRouter(), http.MethodDelete, tt.path(league), "")
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func equalPtr(a, b *string) bool {
	if a == nil || b == nil {
		return a == b
	}
	return *a == *b
}

func deref(s *string) string {
	if s == nil {
		return "<nil>"
	}
	return *s
}
