//go:build integration

package match

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"sync"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"league-s/internal/db"
	"league-s/internal/testdb"
	"league-s/internal/testhttp"
)

type fixture struct {
	router       http.Handler
	seed         *testdb.Seeder
	season       db.Season
	home, away   db.Team
	third        db.Team
	unregistered db.Team
}

func newFixture(t *testing.T) fixture {
	t.Helper()
	s := testdb.New(t, testPool)
	store := NewPostgresStore(testPool)

	r := chi.NewRouter()
	r.Mount("/api/v1/leagues/{leagueID}/seasons/{seasonID}/matches", NewHandler(NewService(store), store).Routes())

	f := fixture{
		router:       r,
		seed:         s,
		season:       s.CreateSeason(testdb.SeasonParams{}),
		home:         s.CreateTeam(testdb.TeamParams{}),
		away:         s.CreateTeam(testdb.TeamParams{}),
		third:        s.CreateTeam(testdb.TeamParams{}),
		unregistered: s.CreateTeam(testdb.TeamParams{}),
	}
	s.RegisterTeams(f.season, f.home, f.away, f.third)
	return f
}

func (f fixture) matchesPath() string {
	return fmt.Sprintf("/api/v1/leagues/%s/seasons/%s/matches", f.season.LeagueID, f.season.ID)
}

func (f fixture) matchPath(id uuid.UUID, action string) string {
	return fmt.Sprintf("%s/%s%s", f.matchesPath(), id, action)
}

func scheduleBody(home, away uuid.UUID, matchday int, kickoffAt string) string {
	if kickoffAt == "" {
		return fmt.Sprintf(`{"home_team_id": %q, "away_team_id": %q, "matchday": %d}`, home, away, matchday)
	}
	return fmt.Sprintf(`{"home_team_id": %q, "away_team_id": %q, "matchday": %d, "kickoff_at": %q}`, home, away, matchday, kickoffAt)
}

func decode[T any](t *testing.T, rec *httptest.ResponseRecorder) T {
	t.Helper()
	var v T
	if err := json.NewDecoder(rec.Body).Decode(&v); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	return v
}

func (f fixture) do(t *testing.T, method, path, body string, wantStatus int) matchResponse {
	t.Helper()
	rec := testhttp.Do(t, f.router, method, path, body)
	if rec.Code != wantStatus {
		t.Fatalf("%s %s: status = %d, want %d, body = %s", method, path, rec.Code, wantStatus, rec.Body)
	}
	return decode[matchResponse](t, rec)
}

func (f fixture) schedule(t *testing.T, home, away db.Team, matchday int) matchResponse {
	t.Helper()
	return f.do(t, http.MethodPost, f.matchesPath(), scheduleBody(home.ID, away.ID, matchday, "2025-10-04T18:00:00Z"), http.StatusCreated)
}

func TestScheduleThenGetMatch(t *testing.T) {
	f := newFixture(t)

	created := f.schedule(t, f.home, f.away, 1)
	switch {
	case created.ID == uuid.Nil:
		t.Error("id is empty, want the id generated by the database")
	case created.Status != StatusScheduled || created.HomeScore != nil || created.AwayScore != nil:
		t.Errorf("match = %+v, want it scheduled without a score", created)
	case created.HomeTeamID != f.home.ID || created.AwayTeamID != f.away.ID || created.Matchday != 1:
		t.Errorf("match = %+v, want home vs away on matchday 1", created)
	case created.KickoffAt == nil:
		t.Error("kickoff_at is empty, want the kickoff sent")
	}

	got := f.do(t, http.MethodGet, f.matchPath(created.ID, ""), "", http.StatusOK)
	if got.ID != created.ID || got.Status != StatusScheduled {
		t.Errorf("get = %+v, want the created match", got)
	}
}

func TestScheduleMatch_Errors(t *testing.T) {
	tests := []struct {
		name       string
		body       func(f fixture) string
		wantStatus int
	}{
		{"invalid JSON", func(fixture) string { return `{"home_team_id":` }, http.StatusBadRequest},
		{"team id is not a uuid", func(f fixture) string {
			return fmt.Sprintf(`{"home_team_id": "abc", "away_team_id": %q, "matchday": 1}`, f.away.ID)
		}, http.StatusUnprocessableEntity},
		{"same team twice", func(f fixture) string { return scheduleBody(f.home.ID, f.home.ID, 1, "") }, http.StatusUnprocessableEntity},
		{"matchday 0", func(f fixture) string { return scheduleBody(f.home.ID, f.away.ID, 0, "") }, http.StatusUnprocessableEntity},
		{"team not registered in the season", func(f fixture) string { return scheduleBody(f.home.ID, f.unregistered.ID, 1, "") }, http.StatusUnprocessableEntity},
		{"kickoff before the season", func(f fixture) string { return scheduleBody(f.home.ID, f.away.ID, 1, "2025-07-31T18:00:00Z") }, http.StatusUnprocessableEntity},
		{"kickoff after the season", func(f fixture) string { return scheduleBody(f.home.ID, f.away.ID, 1, "2026-06-01T18:00:00Z") }, http.StatusUnprocessableEntity},
		{"a team already plays that matchday", func(f fixture) string {
			f.schedule(t, f.home, f.third, 1)
			return scheduleBody(f.away.ID, f.home.ID, 1, "")
		}, http.StatusConflict},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := newFixture(t)
			body := tt.body(f)

			rec := testhttp.Do(t, f.router, http.MethodPost, f.matchesPath(), body)
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func TestScheduleMatch_UnknownSeason(t *testing.T) {
	f := newFixture(t)
	path := fmt.Sprintf("/api/v1/leagues/%s/seasons/%s/matches", f.season.LeagueID, uuid.New())

	rec := testhttp.Do(t, f.router, http.MethodPost, path, scheduleBody(f.home.ID, f.away.ID, 1, ""))
	if rec.Code != http.StatusNotFound {
		t.Errorf("status = %d, want %d, body = %s", rec.Code, http.StatusNotFound, rec.Body)
	}
}

func TestScheduleMatch_ACancelledMatchFreesTheMatchday(t *testing.T) {
	f := newFixture(t)
	m := f.schedule(t, f.home, f.away, 1)
	f.do(t, http.MethodPost, f.matchPath(m.ID, "/cancel"), "", http.StatusOK)

	f.schedule(t, f.home, f.third, 1)
}

func TestScheduleMatch_ConcurrentRequestsKeepOneMatchPerTeamAndMatchday(t *testing.T) {
	f := newFixture(t)
	opponents := []db.Team{f.away, f.third}

	codes := make([]int, len(opponents))
	var wg sync.WaitGroup
	for i, opponent := range opponents {
		wg.Go(func() {
			codes[i] = testhttp.Do(t, f.router, http.MethodPost, f.matchesPath(), scheduleBody(f.home.ID, opponent.ID, 1, "")).Code
		})
	}
	wg.Wait()

	created, refused := 0, 0
	for _, code := range codes {
		switch code {
		case http.StatusCreated:
			created++
		case http.StatusConflict:
			refused++
		}
	}
	if created != 1 || refused != 1 {
		t.Errorf("statuses = %v, want one 201 and one 409", codes)
	}
}

func TestMatch_IsNotReachableFromAnotherLeague(t *testing.T) {
	f := newFixture(t)
	m := f.schedule(t, f.home, f.away, 1)
	other := f.seed.CreateLeague(testdb.LeagueParams{})
	path := fmt.Sprintf("/api/v1/leagues/%s/seasons/%s/matches/%s", other.ID, f.season.ID, m.ID)

	requests := []struct {
		method string
		path   string
		body   string
	}{
		{http.MethodGet, path, ""},
		{http.MethodPatch, path, `{"matchday": 2}`},
		{http.MethodDelete, path, ""},
		{http.MethodPost, path + "/start", ""},
		{http.MethodPost, path + "/cancel", ""},
	}
	for _, rq := range requests {
		if rec := testhttp.Do(t, f.router, rq.method, rq.path, rq.body); rec.Code != http.StatusNotFound {
			t.Errorf("%s %s: status = %d, want %d: the season belongs to another league", rq.method, rq.path, rec.Code, http.StatusNotFound)
		}
	}

	listPath := fmt.Sprintf("/api/v1/leagues/%s/seasons/%s/matches", other.ID, f.season.ID)
	if matches := decode[[]matchResponse](t, testhttp.Do(t, f.router, http.MethodGet, listPath, "")); len(matches) != 0 {
		t.Errorf("list from another league has %d matches, want 0", len(matches))
	}
}

func TestMatchLifecycle(t *testing.T) {
	f := newFixture(t)
	m := f.schedule(t, f.home, f.away, 1)

	started := f.do(t, http.MethodPost, f.matchPath(m.ID, "/start"), "", http.StatusOK)
	if started.Status != StatusLive || started.HomeScore == nil || *started.HomeScore != 0 || *started.AwayScore != 0 {
		t.Errorf("after start: match = %+v, want live at 0-0", started)
	}

	scored := f.do(t, http.MethodPut, f.matchPath(m.ID, "/score"), `{"home": 2, "away": 1}`, http.StatusOK)
	if *scored.HomeScore != 2 || *scored.AwayScore != 1 {
		t.Errorf("after score: %d-%d, want 2-1", *scored.HomeScore, *scored.AwayScore)
	}

	finished := f.do(t, http.MethodPost, f.matchPath(m.ID, "/finish"), "", http.StatusOK)
	if finished.Status != StatusFinished || *finished.HomeScore != 2 || *finished.AwayScore != 1 {
		t.Errorf("after finish: match = %+v, want finished at 2-1", finished)
	}

	got := f.do(t, http.MethodGet, f.matchPath(m.ID, ""), "", http.StatusOK)
	if got.Status != StatusFinished {
		t.Errorf("stored status = %s, want %s", got.Status, StatusFinished)
	}
}

func TestMatch_ForbiddenTransitions(t *testing.T) {
	tests := []struct {
		name    string
		prepare func(f fixture, id uuid.UUID)
		method  string
		action  string
		body    string
	}{
		{"finish a scheduled match", func(fixture, uuid.UUID) {}, http.MethodPost, "/finish", ""},
		{"score a scheduled match", func(fixture, uuid.UUID) {}, http.MethodPut, "/score", `{"home": 1, "away": 0}`},
		{"start a match twice", func(f fixture, id uuid.UUID) {
			f.do(t, http.MethodPost, f.matchPath(id, "/start"), "", http.StatusOK)
		}, http.MethodPost, "/start", ""},
		{"cancel a live match", func(f fixture, id uuid.UUID) {
			f.do(t, http.MethodPost, f.matchPath(id, "/start"), "", http.StatusOK)
		}, http.MethodPost, "/cancel", ""},
		{"postpone a live match", func(f fixture, id uuid.UUID) {
			f.do(t, http.MethodPost, f.matchPath(id, "/start"), "", http.StatusOK)
		}, http.MethodPost, "/postpone", `{}`},
		{"start a cancelled match", func(f fixture, id uuid.UUID) {
			f.do(t, http.MethodPost, f.matchPath(id, "/cancel"), "", http.StatusOK)
		}, http.MethodPost, "/start", ""},
		{"reschedule a cancelled match", func(f fixture, id uuid.UUID) {
			f.do(t, http.MethodPost, f.matchPath(id, "/cancel"), "", http.StatusOK)
		}, http.MethodPatch, "", `{"matchday": 2}`},
		{"delete a live match", func(f fixture, id uuid.UUID) {
			f.do(t, http.MethodPost, f.matchPath(id, "/start"), "", http.StatusOK)
		}, http.MethodDelete, "", ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := newFixture(t)
			m := f.schedule(t, f.home, f.away, 1)
			tt.prepare(f, m.ID)

			rec := testhttp.Do(t, f.router, tt.method, f.matchPath(m.ID, tt.action), tt.body)
			if rec.Code != http.StatusConflict {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, http.StatusConflict, rec.Body)
			}
		})
	}
}

func TestSetScore_Validation(t *testing.T) {
	f := newFixture(t)
	m := f.schedule(t, f.home, f.away, 1)
	f.do(t, http.MethodPost, f.matchPath(m.ID, "/start"), "", http.StatusOK)

	for _, body := range []string{`{"home": -1, "away": 0}`, `{"home": 1}`, `{}`} {
		if rec := testhttp.Do(t, f.router, http.MethodPut, f.matchPath(m.ID, "/score"), body); rec.Code != http.StatusUnprocessableEntity {
			t.Errorf("body %s: status = %d, want %d", body, rec.Code, http.StatusUnprocessableEntity)
		}
	}
}

func TestPostponeMatch(t *testing.T) {
	f := newFixture(t)
	m := f.schedule(t, f.home, f.away, 1)

	postponed := f.do(t, http.MethodPost, f.matchPath(m.ID, "/postpone"), `{}`, http.StatusOK)
	if postponed.Status != StatusPostponed || postponed.KickoffAt != nil {
		t.Errorf("after postpone: match = %+v, want postponed without a kickoff", postponed)
	}

	rescheduled := f.do(t, http.MethodPatch, f.matchPath(m.ID, ""), `{"kickoff_at": "2025-11-08T18:00:00Z"}`, http.StatusOK)
	if rescheduled.Status != StatusScheduled || rescheduled.KickoffAt == nil {
		t.Errorf("after a new kickoff: match = %+v, want it scheduled again", rescheduled)
	}
}

func TestPostponeMatch_WithANewDate(t *testing.T) {
	f := newFixture(t)
	m := f.schedule(t, f.home, f.away, 1)

	got := f.do(t, http.MethodPost, f.matchPath(m.ID, "/postpone"), `{"kickoff_at": "2025-11-08T18:00:00Z"}`, http.StatusOK)
	if got.Status != StatusScheduled || got.KickoffAt == nil || got.KickoffAt.Day() != 8 {
		t.Errorf("match = %+v, want it scheduled at the new kickoff", got)
	}

	rec := testhttp.Do(t, f.router, http.MethodPost, f.matchPath(m.ID, "/postpone"), `{"kickoff_at": "2026-06-01T18:00:00Z"}`)
	if rec.Code != http.StatusUnprocessableEntity {
		t.Errorf("new date outside the season: status = %d, want %d", rec.Code, http.StatusUnprocessableEntity)
	}
}

func TestRescheduleMatch_Errors(t *testing.T) {
	tests := []struct {
		name       string
		body       string
		wantStatus int
	}{
		{"nothing to change", `{}`, http.StatusUnprocessableEntity},
		{"matchday 0", `{"matchday": 0}`, http.StatusUnprocessableEntity},
		{"kickoff outside the season", `{"kickoff_at": "2026-06-01T18:00:00Z"}`, http.StatusUnprocessableEntity},
		{"a team already plays that matchday", `{"matchday": 2}`, http.StatusConflict},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := newFixture(t)
			m := f.schedule(t, f.home, f.away, 1)
			f.schedule(t, f.home, f.third, 2)

			rec := testhttp.Do(t, f.router, http.MethodPatch, f.matchPath(m.ID, ""), tt.body)
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func TestRescheduleMatch_KeepingItsOwnMatchdayIsAllowed(t *testing.T) {
	f := newFixture(t)
	m := f.schedule(t, f.home, f.away, 1)

	got := f.do(t, http.MethodPatch, f.matchPath(m.ID, ""), `{"matchday": 1, "kickoff_at": "2025-10-05T15:00:00Z"}`, http.StatusOK)
	if got.Matchday != 1 || got.KickoffAt == nil || got.KickoffAt.Day() != 5 {
		t.Errorf("match = %+v, want matchday 1 at the new kickoff", got)
	}
}

func TestDeleteMatch(t *testing.T) {
	f := newFixture(t)
	m := f.schedule(t, f.home, f.away, 1)

	if rec := testhttp.Do(t, f.router, http.MethodDelete, f.matchPath(m.ID, ""), ""); rec.Code != http.StatusNoContent {
		t.Fatalf("delete: status = %d, want %d, body = %s", rec.Code, http.StatusNoContent, rec.Body)
	}
	if rec := testhttp.Do(t, f.router, http.MethodGet, f.matchPath(m.ID, ""), ""); rec.Code != http.StatusNotFound {
		t.Errorf("get after delete: status = %d, want %d", rec.Code, http.StatusNotFound)
	}
	if rec := testhttp.Do(t, f.router, http.MethodDelete, f.matchPath(m.ID, ""), ""); rec.Code != http.StatusNotFound {
		t.Errorf("second delete: status = %d, want %d", rec.Code, http.StatusNotFound)
	}
}

func TestListMatches_Filters(t *testing.T) {
	f := newFixture(t)
	first := f.do(t, http.MethodPost, f.matchesPath(), scheduleBody(f.home.ID, f.away.ID, 1, "2025-10-04T18:00:00Z"), http.StatusCreated)
	second := f.do(t, http.MethodPost, f.matchesPath(), scheduleBody(f.away.ID, f.third.ID, 2, "2025-10-11T18:00:00Z"), http.StatusCreated)
	undated := f.do(t, http.MethodPost, f.matchesPath(), scheduleBody(f.third.ID, f.home.ID, 3, ""), http.StatusCreated)

	tests := []struct {
		name  string
		query string
		want  []uuid.UUID
	}{
		{"everything, by matchday", "", []uuid.UUID{first.ID, second.ID, undated.ID}},
		{"one matchday", "?matchday=2", []uuid.UUID{second.ID}},
		{"one team", "?team=" + f.home.ID.String(), []uuid.UUID{first.ID, undated.ID}},
		{"from a date", "?from=2025-10-11", []uuid.UUID{second.ID}},
		{"until a date, included", "?to=2025-10-04", []uuid.UUID{first.ID}},
		{"between two dates", "?from=2025-10-01&to=2025-10-31", []uuid.UUID{first.ID, second.ID}},
		{"team and matchday", "?matchday=1&team=" + f.third.ID.String(), nil},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rec := testhttp.Do(t, f.router, http.MethodGet, f.matchesPath()+tt.query, "")
			if rec.Code != http.StatusOK {
				t.Fatalf("status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
			}

			matches := decode[[]matchResponse](t, rec)
			got := make([]uuid.UUID, len(matches))
			for i, m := range matches {
				got[i] = m.ID
			}
			if fmt.Sprint(got) != fmt.Sprint(append([]uuid.UUID{}, tt.want...)) {
				t.Errorf("matches = %v, want %v", got, tt.want)
			}
		})
	}

	for _, query := range []string{"?matchday=abc", "?matchday=0", "?from=04/10/2025", "?to=tomorrow", "?team=abc"} {
		if rec := testhttp.Do(t, f.router, http.MethodGet, f.matchesPath()+query, ""); rec.Code != http.StatusBadRequest {
			t.Errorf("%s: status = %d, want %d", query, rec.Code, http.StatusBadRequest)
		}
	}
}
