//go:build integration

package season

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"league-s/internal/db"
	"league-s/internal/testdb"
	"league-s/internal/testhttp"
)

func newTestRouter() http.Handler {
	r := chi.NewRouter()
	r.Mount("/api/v1/leagues/{leagueID}/seasons", NewHandler(NewPostgresStore(testPool)).Routes())
	return r
}

func seasonsPath(l db.League) string {
	return fmt.Sprintf("/api/v1/leagues/%s/seasons", l.ID)
}

func seasonPath(s db.Season) string {
	return fmt.Sprintf("/api/v1/leagues/%s/seasons/%s", s.LeagueID, s.ID)
}

func seasonTeamPath(s db.Season, t db.Team) string {
	return fmt.Sprintf("%s/teams/%s", seasonPath(s), t.ID)
}

const validSeasonBody = `{
	"name": "2025-2026",
	"start_on": "2025-08-01T00:00:00Z",
	"end_on": "2026-05-31T00:00:00Z",
	"match_win_pts": 3,
	"match_draw_pts": 1,
	"match_loss_pts": 0,
	"tie_breakers": ["goal_difference", "head_to_head"]
}`

func TestCreateThenGetSeason(t *testing.T) {
	league := testdb.New(t, testPool).CreateLeague(testdb.LeagueParams{})
	router := newTestRouter()

	rec := testhttp.Do(t, router, http.MethodPost, seasonsPath(league), validSeasonBody)
	if rec.Code != http.StatusCreated {
		t.Fatalf("create: status = %d, want %d, body = %s", rec.Code, http.StatusCreated, rec.Body)
	}

	var created seasonResponse
	if err := json.NewDecoder(rec.Body).Decode(&created); err != nil {
		t.Fatalf("decode create response: %v", err)
	}
	if created.ID == uuid.Nil {
		t.Fatal("create: id is 0, want the id generated by the database")
	}

	rec = testhttp.Do(t, router, http.MethodGet, fmt.Sprintf("%s/%s", seasonsPath(league), created.ID), "")
	if rec.Code != http.StatusOK {
		t.Fatalf("get: status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}

	var got seasonResponse
	if err := json.NewDecoder(rec.Body).Decode(&got); err != nil {
		t.Fatalf("decode get response: %v", err)
	}

	wantStart := time.Date(2025, time.August, 1, 0, 0, 0, 0, time.UTC)
	wantEnd := time.Date(2026, time.May, 31, 0, 0, 0, 0, time.UTC)
	switch {
	case got.Name != "2025-2026":
		t.Errorf("name = %q, want %q", got.Name, "2025-2026")
	case !got.StartOn.Equal(wantStart):
		t.Errorf("start_on = %v, want %v", got.StartOn, wantStart)
	case !got.EndOn.Equal(wantEnd):
		t.Errorf("end_on = %v, want %v", got.EndOn, wantEnd)
	case got.MatchWinPts != 3 || got.MatchDrawPts != 1 || got.MatchLossPts != 0:
		t.Errorf("points = %d/%d/%d, want 3/1/0", got.MatchWinPts, got.MatchDrawPts, got.MatchLossPts)
	case !slices.Equal(got.TieBreakers, []string{"goal_difference", "head_to_head"}):
		t.Errorf("tie_breakers = %v, want [goal_difference head_to_head]", got.TieBreakers)
	case got.LeagueID != league.ID:
		t.Errorf("league_id = %s, want %s (from the URL)", got.LeagueID, league.ID)
	}
}

func TestCreateSeason_SameNameInAnotherLeague(t *testing.T) {
	s := testdb.New(t, testPool)
	s.CreateSeason(testdb.SeasonParams{Name: "2025-2026"})
	other := s.CreateLeague(testdb.LeagueParams{})

	rec := testhttp.Do(t, newTestRouter(), http.MethodPost, seasonsPath(other), validSeasonBody)
	if rec.Code != http.StatusCreated {
		t.Errorf("status = %d, want %d: names are unique per league only, body = %s", rec.Code, http.StatusCreated, rec.Body)
	}
}

func TestCreateSeason_Errors(t *testing.T) {
	withField := func(field, value string) string {
		var m map[string]json.RawMessage
		if err := json.Unmarshal([]byte(validSeasonBody), &m); err != nil {
			panic(err)
		}
		if value == "" {
			delete(m, field)
		} else {
			m[field] = json.RawMessage(value)
		}
		b, _ := json.Marshal(m)
		return string(b)
	}

	tests := []struct {
		name       string
		path       func(l db.League) string
		body       string
		wantStatus int
	}{
		{"invalid JSON", seasonsPath, `{"name":`, http.StatusBadRequest},
		{"missing name", seasonsPath, withField("name", ""), http.StatusUnprocessableEntity},
		{"name too long", seasonsPath, withField("name", `"`+strings.Repeat("a", 51)+`"`), http.StatusUnprocessableEntity},
		{"end before start", seasonsPath, withField("end_on", `"2025-01-01T00:00:00Z"`), http.StatusUnprocessableEntity},
		{"negative points", seasonsPath, withField("match_win_pts", `-1`), http.StatusUnprocessableEntity},
		{"unknown tie breaker", seasonsPath, withField("tie_breakers", `["coin_flip"]`), http.StatusUnprocessableEntity},
		{"same name in the same league", seasonsPath, validSeasonBody, http.StatusConflict},
		{"unknown league", func(db.League) string { return "/api/v1/leagues/" + uuid.NewString() + "/seasons" }, validSeasonBody, http.StatusNotFound},
		{"invalid league id", func(db.League) string { return "/api/v1/leagues/abc/seasons" }, validSeasonBody, http.StatusBadRequest},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := testdb.New(t, testPool)
			league := s.CreateLeague(testdb.LeagueParams{})
			s.CreateSeason(testdb.SeasonParams{League: &league, Name: "2025-2026"})

			rec := testhttp.Do(t, newTestRouter(), http.MethodPost, tt.path(league), tt.body)
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func TestGetSeason_Errors(t *testing.T) {
	type fixture struct {
		season db.Season
		other  db.League
	}
	tests := []struct {
		name       string
		path       func(f fixture) string
		wantStatus int
	}{
		{
			name: "unknown id",
			path: func(f fixture) string {
				return fmt.Sprintf("/api/v1/leagues/%s/seasons/%s", f.season.LeagueID, uuid.NewString())
			},
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "season of another league",
			path:       func(f fixture) string { return fmt.Sprintf("%s/%s", seasonsPath(f.other), f.season.ID) },
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "invalid id",
			path:       func(f fixture) string { return fmt.Sprintf("/api/v1/leagues/%s/seasons/abc", f.season.LeagueID) },
			wantStatus: http.StatusBadRequest,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := testdb.New(t, testPool)
			f := fixture{season: s.CreateSeason(testdb.SeasonParams{}), other: s.CreateLeague(testdb.LeagueParams{})}

			rec := testhttp.Do(t, newTestRouter(), http.MethodGet, tt.path(f), "")
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func TestListSeasons(t *testing.T) {
	s := testdb.New(t, testPool)
	league := s.CreateLeague(testdb.LeagueParams{})
	other := s.CreateLeague(testdb.LeagueParams{})
	s.CreateSeason(testdb.SeasonParams{League: &league, Name: "2024-2025", StartOn: "2024-08-01", EndOn: "2025-05-31"})
	s.CreateSeason(testdb.SeasonParams{League: &league, Name: "2025-2026", StartOn: "2025-08-01", EndOn: "2026-05-31"})
	s.CreateSeason(testdb.SeasonParams{League: &other, Name: "Other league"})

	rec := testhttp.Do(t, newTestRouter(), http.MethodGet, seasonsPath(league), "")
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}

	var seasons []seasonResponse
	if err := json.NewDecoder(rec.Body).Decode(&seasons); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if len(seasons) != 2 || seasons[0].Name != "2025-2026" || seasons[1].Name != "2024-2025" {
		t.Errorf("seasons = %+v, want the two seasons of the league, most recent first", seasons)
	}
}

func TestListSeasons_Empty(t *testing.T) {
	league := testdb.New(t, testPool).CreateLeague(testdb.LeagueParams{})

	rec := testhttp.Do(t, newTestRouter(), http.MethodGet, seasonsPath(league), "")
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}
	if body := strings.TrimSpace(rec.Body.String()); body != "[]" {
		t.Errorf("body = %s, want an empty JSON array", body)
	}
}

func TestAddTeamThenListTeams(t *testing.T) {
	s := testdb.New(t, testPool)
	season := s.CreateSeason(testdb.SeasonParams{})
	lyon := s.CreateTeam(testdb.TeamParams{Name: "Lyon"})
	lens := s.CreateTeam(testdb.TeamParams{Name: "Lens"})
	s.CreateTeam(testdb.TeamParams{Name: "Nantes"})
	router := newTestRouter()

	for _, team := range []db.Team{lyon, lens} {
		rec := testhttp.Do(t, router, http.MethodPost, seasonTeamPath(season, team), "")
		if rec.Code != http.StatusOK {
			t.Fatalf("add team %q: status = %d, want %d, body = %s", team.Name, rec.Code, http.StatusOK, rec.Body)
		}
	}

	rec := testhttp.Do(t, router, http.MethodGet, seasonPath(season)+"/teams", "")
	if rec.Code != http.StatusOK {
		t.Fatalf("list: status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}

	var got []struct {
		ID   uuid.UUID `json:"id"`
		Name string    `json:"name"`
	}
	if err := json.NewDecoder(rec.Body).Decode(&got); err != nil {
		t.Fatalf("decode list response: %v, body = %s", err, rec.Body)
	}

	var names []string
	for _, team := range got {
		names = append(names, team.Name)
	}
	if !slices.Equal(names, []string{"Lens", "Lyon"}) {
		t.Errorf("teams = %v, want [Lens Lyon] (registered teams, sorted by name)", names)
	}
}

func TestListTeams_Empty(t *testing.T) {
	t.Run("season without teams", func(t *testing.T) {
		s := testdb.New(t, testPool)
		season := s.CreateSeason(testdb.SeasonParams{})
		s.CreateTeam(testdb.TeamParams{})

		assertEmptyList(t, seasonPath(season)+"/teams")
	})

	t.Run("season of another league", func(t *testing.T) {
		s := testdb.New(t, testPool)
		season := s.CreateSeason(testdb.SeasonParams{})
		s.RegisterTeams(season, s.CreateTeam(testdb.TeamParams{}))
		other := s.CreateLeague(testdb.LeagueParams{})

		assertEmptyList(t, fmt.Sprintf("%s/%s/teams", seasonsPath(other), season.ID))
	})
}

func assertEmptyList(t *testing.T, path string) {
	t.Helper()
	rec := testhttp.Do(t, newTestRouter(), http.MethodGet, path, "")
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}
	if body := strings.TrimSpace(rec.Body.String()); body != "[]" {
		t.Errorf("body = %s, want []", body)
	}
}

func TestAddTeam_Errors(t *testing.T) {
	type fixture struct {
		season              db.Season
		other               db.League
		registered, free    db.Team
		teamOfAnotherLeague db.Team
	}
	tests := []struct {
		name       string
		path       func(f fixture) string
		wantStatus int
	}{
		{
			name:       "already registered",
			path:       func(f fixture) string { return seasonTeamPath(f.season, f.registered) },
			wantStatus: http.StatusConflict,
		},
		{
			name: "unknown season",
			path: func(f fixture) string {
				return fmt.Sprintf("/api/v1/leagues/%s/seasons/%s/teams/%s", f.season.LeagueID, uuid.NewString(), f.free.ID)
			},
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "unknown team",
			path:       func(f fixture) string { return seasonPath(f.season) + "/teams/" + uuid.NewString() },
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "team of another league",
			path:       func(f fixture) string { return seasonTeamPath(f.season, f.teamOfAnotherLeague) },
			wantStatus: http.StatusNotFound,
		},
		{
			name: "season of another league",
			path: func(f fixture) string {
				return fmt.Sprintf("%s/%s/teams/%s", seasonsPath(f.other), f.season.ID, f.teamOfAnotherLeague.ID)
			},
			wantStatus: http.StatusNotFound,
		},
		{
			name: "invalid season id",
			path: func(f fixture) string {
				return fmt.Sprintf("/api/v1/leagues/%s/seasons/abc/teams/%s", f.season.LeagueID, f.free.ID)
			},
			wantStatus: http.StatusBadRequest,
		},
		{
			name:       "invalid team id",
			path:       func(f fixture) string { return seasonPath(f.season) + "/teams/abc" },
			wantStatus: http.StatusBadRequest,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := testdb.New(t, testPool)
			f := fixture{season: s.CreateSeason(testdb.SeasonParams{}), registered: s.CreateTeam(testdb.TeamParams{}), free: s.CreateTeam(testdb.TeamParams{}), other: s.CreateLeague(testdb.LeagueParams{})}
			f.teamOfAnotherLeague = s.CreateTeam(testdb.TeamParams{League: &f.other})
			s.RegisterTeams(f.season, f.registered)

			rec := testhttp.Do(t, newTestRouter(), http.MethodPost, tt.path(f), "")
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func TestRemoveTeam(t *testing.T) {
	s := testdb.New(t, testPool)
	season := s.CreateSeason(testdb.SeasonParams{})
	team := s.CreateTeam(testdb.TeamParams{})
	s.RegisterTeams(season, team)

	rec := testhttp.Do(t, newTestRouter(), http.MethodDelete, seasonTeamPath(season, team), "")
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}

	var count int
	err := testPool.QueryRow(context.Background(),
		`SELECT count(*) FROM season_team WHERE season_id = $1 AND team_id = $2`, season.ID, team.ID).Scan(&count)
	if err != nil {
		t.Fatalf("count registrations: %v", err)
	}
	if count != 0 {
		t.Errorf("team is still registered after delete")
	}
}

func TestRemoveTeam_Errors(t *testing.T) {
	type fixture struct {
		season                    db.Season
		other                     db.League
		home, away, notRegistered db.Team
	}
	tests := []struct {
		name       string
		path       func(f fixture) string
		wantStatus int
	}{
		{
			name:       "team not registered",
			path:       func(f fixture) string { return seasonTeamPath(f.season, f.notRegistered) },
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "team has a home match",
			path:       func(f fixture) string { return seasonTeamPath(f.season, f.home) },
			wantStatus: http.StatusConflict,
		},
		{
			name:       "team has an away match",
			path:       func(f fixture) string { return seasonTeamPath(f.season, f.away) },
			wantStatus: http.StatusConflict,
		},
		{
			name: "season of another league",
			path: func(f fixture) string {
				return fmt.Sprintf("%s/%s/teams/%s", seasonsPath(f.other), f.season.ID, f.home.ID)
			},
			wantStatus: http.StatusNotFound,
		},
		{
			name: "invalid season id",
			path: func(f fixture) string {
				return fmt.Sprintf("/api/v1/leagues/%s/seasons/abc/teams/%s", f.season.LeagueID, f.home.ID)
			},
			wantStatus: http.StatusBadRequest,
		},
		{
			name:       "invalid team id",
			path:       func(f fixture) string { return seasonPath(f.season) + "/teams/abc" },
			wantStatus: http.StatusBadRequest,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := testdb.New(t, testPool)
			f := fixture{season: s.CreateSeason(testdb.SeasonParams{}), home: s.CreateTeam(testdb.TeamParams{}), away: s.CreateTeam(testdb.TeamParams{}), notRegistered: s.CreateTeam(testdb.TeamParams{}), other: s.CreateLeague(testdb.LeagueParams{})}
			s.RegisterTeams(f.season, f.home, f.away)
			s.CreateMatch(testdb.MatchParams{Season: f.season, Home: f.home, Away: f.away, Matchday: 1})

			rec := testhttp.Do(t, newTestRouter(), http.MethodDelete, tt.path(f), "")
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}
