//go:build integration

package player

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"league-s/internal/db"
	"league-s/internal/testdb"
	"league-s/internal/testhttp"
)

func newTestRouter() http.Handler {
	r := chi.NewRouter()
	r.Mount("/api/v1/leagues/{leagueID}/players", NewHandler(NewPostgresStore(testPool)).Routes())
	return r
}

func playersPath(l db.League) string {
	return fmt.Sprintf("/api/v1/leagues/%s/players", l.ID)
}

func TestCreateThenGetPlayer(t *testing.T) {
	tests := []struct {
		name     string
		body     string
		wantIcon *string
	}{
		{
			name:     "with icon",
			body:     `{"firstname": "Jean", "lastname": "Dupont", "icon": "https://example.com/dupont.png"}`,
			wantIcon: new("https://example.com/dupont.png"),
		},
		{
			name:     "without icon",
			body:     `{"firstname": "Jean", "lastname": "Dupont"}`,
			wantIcon: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			league := testdb.New(t, testPool).CreateLeague(testdb.LeagueParams{})
			router := newTestRouter()

			rec := testhttp.Do(t, router, http.MethodPost, playersPath(league), tt.body)
			if rec.Code != http.StatusCreated {
				t.Fatalf("create: status = %d, want %d, body = %s", rec.Code, http.StatusCreated, rec.Body)
			}

			var created playerResponse
			if err := json.NewDecoder(rec.Body).Decode(&created); err != nil {
				t.Fatalf("decode create response: %v", err)
			}
			if created.ID == uuid.Nil {
				t.Fatal("create: id is 0, want the id generated by the database")
			}
			if created.LeagueID != league.ID {
				t.Errorf("create: league_id = %s, want %s (from the URL)", created.LeagueID, league.ID)
			}

			rec = testhttp.Do(t, router, http.MethodGet, fmt.Sprintf("%s/%s", playersPath(league), created.ID), "")
			if rec.Code != http.StatusOK {
				t.Fatalf("get: status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
			}

			var got playerResponse
			if err := json.NewDecoder(rec.Body).Decode(&got); err != nil {
				t.Fatalf("decode get response: %v", err)
			}
			if got.Firstname != "Jean" || got.Lastname != "Dupont" {
				t.Errorf("get: got %s %s, want Jean Dupont", got.Firstname, got.Lastname)
			}
			if !equalPtr(got.Icon, tt.wantIcon) {
				t.Errorf("get: icon = %v, want %v", deref(got.Icon), deref(tt.wantIcon))
			}
		})
	}
}

func TestCreatePlayer_Errors(t *testing.T) {
	const valid = `{"firstname": "Jean", "lastname": "Dupont"}`
	tests := []struct {
		name       string
		path       func(l db.League) string
		body       string
		wantStatus int
	}{
		{"invalid JSON", playersPath, `{"firstname":`, http.StatusBadRequest},
		{"missing firstname", playersPath, `{"lastname": "Dupont"}`, http.StatusUnprocessableEntity},
		{"missing lastname", playersPath, `{"firstname": "Jean"}`, http.StatusUnprocessableEntity},
		{"firstname too long", playersPath, `{"firstname": "` + strings.Repeat("a", 51) + `", "lastname": "Dupont"}`, http.StatusUnprocessableEntity},
		{"lastname too long", playersPath, `{"firstname": "Jean", "lastname": "` + strings.Repeat("a", 51) + `"}`, http.StatusUnprocessableEntity},
		{"icon is not a URL", playersPath, `{"firstname": "Jean", "lastname": "Dupont", "icon": "not a url"}`, http.StatusUnprocessableEntity},
		{"unknown league", func(db.League) string { return "/api/v1/leagues/" + uuid.NewString() + "/players" }, valid, http.StatusNotFound},
		{"invalid league id", func(db.League) string { return "/api/v1/leagues/abc/players" }, valid, http.StatusBadRequest},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			league := testdb.New(t, testPool).CreateLeague(testdb.LeagueParams{})
			rec := testhttp.Do(t, newTestRouter(), http.MethodPost, tt.path(league), tt.body)
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func TestGetPlayer_Errors(t *testing.T) {
	type fixture struct {
		league, other db.League
		player        db.Player
	}
	tests := []struct {
		name       string
		path       func(f fixture) string
		wantStatus int
	}{
		{
			name:       "unknown id",
			path:       func(f fixture) string { return playersPath(f.league) + "/" + uuid.NewString() },
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "player of another league",
			path:       func(f fixture) string { return fmt.Sprintf("%s/%s", playersPath(f.other), f.player.ID) },
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "invalid id",
			path:       func(f fixture) string { return playersPath(f.league) + "/abc" },
			wantStatus: http.StatusBadRequest,
		},
		{
			name:       "invalid league id",
			path:       func(f fixture) string { return fmt.Sprintf("/api/v1/leagues/abc/players/%s", f.player.ID) },
			wantStatus: http.StatusBadRequest,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := testdb.New(t, testPool)
			f := fixture{league: s.CreateLeague(testdb.LeagueParams{}), other: s.CreateLeague(testdb.LeagueParams{})}
			f.player = s.CreatePlayer(testdb.PlayerParams{League: &f.league})

			rec := testhttp.Do(t, newTestRouter(), http.MethodGet, tt.path(f), "")
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func equalPtr(a, b *string) bool {
	if a == nil || b == nil {
		return a == b
	}
	return *a == *b
}

func deref(s *string) string {
	if s == nil {
		return "<nil>"
	}
	return *s
}
