//go:build integration

package squadmembership

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"league-s/internal/db"
	"league-s/internal/testdb"
	"league-s/internal/testhttp"
)

func newTestRouter() http.Handler {
	store := NewPostgresStore(testPool)
	h := NewHandler(NewService(store), store)

	r := chi.NewRouter()
	r.Mount("/api/v1/leagues/{leagueID}/seasons/{seasonID}/teams/{teamID}/squad", h.Routes())
	r.Mount("/api/v1/leagues/{leagueID}/seasons/{seasonID}/transfers", h.TransferRoutes())
	return r
}

func (f fixture) squadPath(team db.Team) string {
	return fmt.Sprintf("/api/v1/leagues/%s/seasons/%s/teams/%s/squad", f.season.LeagueID, f.season.ID, team.ID)
}

func (f fixture) transfersPath() string {
	return fmt.Sprintf("/api/v1/leagues/%s/seasons/%s/transfers", f.season.LeagueID, f.season.ID)
}

func joinBody(playerID uuid.UUID, number, joinedOn string) string {
	return fmt.Sprintf(`{"player_id": %q, "number": %s, "joined_on": %q}`, playerID, number, joinedOn)
}

func decode[T any](t *testing.T, rec *httptest.ResponseRecorder) T {
	t.Helper()
	var v T
	if err := json.NewDecoder(rec.Body).Decode(&v); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	return v
}

func TestJoinThenListSquad(t *testing.T) {
	f := newFixture(t)
	router := newTestRouter()

	rec := testhttp.Do(t, router, http.MethodPost, f.squadPath(f.home), joinBody(f.player.ID, "10", "2025-08-01"))
	if rec.Code != http.StatusCreated {
		t.Fatalf("join: status = %d, want %d, body = %s", rec.Code, http.StatusCreated, rec.Body)
	}
	created := decode[membershipResponse](t, rec)
	switch {
	case created.ID == uuid.Nil:
		t.Error("join: id is empty, want the id generated by the database")
	case created.PlayerID != f.player.ID || created.TeamID != f.home.ID || created.SeasonID != f.season.ID:
		t.Errorf("join: membership = %+v, want the player in the home team for the season", created)
	case created.Number == nil || *created.Number != 10:
		t.Errorf("join: number = %v, want 10", created.Number)
	case created.JoinedOn != "2025-08-01" || created.LeftOn != nil:
		t.Errorf("join: dates = %s / %v, want 2025-08-01 and no leaving date", created.JoinedOn, created.LeftOn)
	}

	rec = testhttp.Do(t, router, http.MethodGet, f.squadPath(f.home), "")
	if rec.Code != http.StatusOK {
		t.Fatalf("list: status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}
	members := decode[[]memberResponse](t, rec)
	if len(members) != 1 || members[0].MembershipID != created.ID || members[0].PlayerID != f.player.ID {
		t.Errorf("list: members = %+v, want the player with membership %s", members, created.ID)
	}
}

func TestJoinSquad_Errors(t *testing.T) {
	tests := []struct {
		name       string
		path       func(f fixture) string
		body       func(f fixture) string
		wantStatus int
	}{
		{
			name:       "invalid JSON",
			path:       func(f fixture) string { return f.squadPath(f.home) },
			body:       func(fixture) string { return `{"player_id":` },
			wantStatus: http.StatusBadRequest,
		},
		{
			name: "invalid team id",
			path: func(f fixture) string {
				return fmt.Sprintf("/api/v1/leagues/%s/seasons/%s/teams/abc/squad", f.season.LeagueID, f.season.ID)
			},
			body:       func(f fixture) string { return joinBody(f.player.ID, "10", "2025-08-01") },
			wantStatus: http.StatusBadRequest,
		},
		{
			name:       "player id is not a uuid",
			path:       func(f fixture) string { return f.squadPath(f.home) },
			body:       func(fixture) string { return `{"player_id": "abc", "joined_on": "2025-08-01"}` },
			wantStatus: http.StatusUnprocessableEntity,
		},
		{
			name:       "missing joining date",
			path:       func(f fixture) string { return f.squadPath(f.home) },
			body:       func(f fixture) string { return fmt.Sprintf(`{"player_id": %q}`, f.player.ID) },
			wantStatus: http.StatusUnprocessableEntity,
		},
		{
			name:       "joining date with a time",
			path:       func(f fixture) string { return f.squadPath(f.home) },
			body:       func(f fixture) string { return joinBody(f.player.ID, "10", "2025-08-01T00:00:00Z") },
			wantStatus: http.StatusUnprocessableEntity,
		},
		{
			name:       "number out of range",
			path:       func(f fixture) string { return f.squadPath(f.home) },
			body:       func(f fixture) string { return joinBody(f.player.ID, "100", "2025-08-01") },
			wantStatus: http.StatusUnprocessableEntity,
		},
		{
			name:       "joining outside the season",
			path:       func(f fixture) string { return f.squadPath(f.home) },
			body:       func(f fixture) string { return joinBody(f.player.ID, "10", "2025-07-31") },
			wantStatus: http.StatusUnprocessableEntity,
		},
		{
			name:       "unknown player",
			path:       func(f fixture) string { return f.squadPath(f.home) },
			body:       func(fixture) string { return joinBody(uuid.New(), "10", "2025-08-01") },
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "team not registered in the season",
			path:       func(f fixture) string { return f.squadPath(f.unregistered) },
			body:       func(f fixture) string { return joinBody(f.player.ID, "10", "2025-08-01") },
			wantStatus: http.StatusNotFound,
		},
		{
			name: "player already in a squad",
			path: func(f fixture) string { return f.squadPath(f.home) },
			body: func(f fixture) string {
				f.join(t, f.away, f.player, nil, "2025-08-01")
				return joinBody(f.player.ID, "10", "2025-08-01")
			},
			wantStatus: http.StatusConflict,
		},
		{
			name: "number already taken",
			path: func(f fixture) string { return f.squadPath(f.home) },
			body: func(f fixture) string {
				f.join(t, f.home, f.seed.CreatePlayer(testdb.PlayerParams{}), new(int32(10)), "2025-08-01")
				return joinBody(f.player.ID, "10", "2025-08-01")
			},
			wantStatus: http.StatusConflict,
		},
		{
			name: "squad full",
			path: func(f fixture) string { return f.squadPath(f.home) },
			body: func(f fixture) string {
				f.setMaxSquadSize(t, 1)
				f.join(t, f.home, f.seed.CreatePlayer(testdb.PlayerParams{}), nil, "2025-08-01")
				return joinBody(f.player.ID, "10", "2025-08-01")
			},
			wantStatus: http.StatusConflict,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := newFixture(t)
			body := tt.body(f)

			rec := testhttp.Do(t, newTestRouter(), http.MethodPost, tt.path(f), body)
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func TestJoinSquad_PlayerOfAnotherLeague(t *testing.T) {
	f := newFixture(t)
	other := f.seed.CreateLeague(testdb.LeagueParams{})
	outsider := f.seed.CreatePlayer(testdb.PlayerParams{League: &other})

	rec := testhttp.Do(t, newTestRouter(), http.MethodPost, f.squadPath(f.home), joinBody(outsider.ID, "null", "2025-08-01"))
	if rec.Code != http.StatusNotFound {
		t.Errorf("status = %d, want %d: a player of another league must not be reachable, body = %s", rec.Code, http.StatusNotFound, rec.Body)
	}
}

func TestListSquad_HistoryIsOptIn(t *testing.T) {
	f := newFixture(t)
	router := newTestRouter()
	m := f.join(t, f.home, f.player, nil, "2025-08-01")
	if _, err := f.store.Leave(t.Context(), f.season.LeagueID, f.season.ID, f.home.ID, f.player.ID, day(t, "2025-12-31")); err != nil {
		t.Fatalf("Leave() error = %v", err)
	}

	rec := testhttp.Do(t, router, http.MethodGet, f.squadPath(f.home), "")
	if members := decode[[]memberResponse](t, rec); len(members) != 0 {
		t.Errorf("default list has %d members, want 0: players who left are hidden", len(members))
	}

	rec = testhttp.Do(t, router, http.MethodGet, f.squadPath(f.home)+"?all=true", "")
	members := decode[[]memberResponse](t, rec)
	if len(members) != 1 || members[0].MembershipID != m.ID || members[0].LeftOn == nil || *members[0].LeftOn != "2025-12-31" {
		t.Errorf("history = %+v, want the closed stint with its leaving date", members)
	}
}

func TestChangeSquadNumber(t *testing.T) {
	f := newFixture(t)
	router := newTestRouter()
	m := f.join(t, f.home, f.player, new(int32(10)), "2025-08-01")
	path := fmt.Sprintf("%s/%s", f.squadPath(f.home), m.ID)

	rec := testhttp.Do(t, router, http.MethodPatch, path, `{"number": 7}`)
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}
	if got := decode[membershipResponse](t, rec); got.Number == nil || *got.Number != 7 {
		t.Errorf("number = %v, want 7", got.Number)
	}

	rec = testhttp.Do(t, router, http.MethodPatch, path, `{"number": null}`)
	if rec.Code != http.StatusOK {
		t.Fatalf("clear: status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}
	if got := decode[membershipResponse](t, rec); got.Number != nil {
		t.Errorf("number = %v, want it cleared", *got.Number)
	}
}

func TestChangeSquadNumber_Errors(t *testing.T) {
	tests := []struct {
		name       string
		id         func(f fixture, m *Membership) uuid.UUID
		body       string
		wantStatus int
	}{
		{"number out of range", func(_ fixture, m *Membership) uuid.UUID { return m.ID }, `{"number": 0}`, http.StatusUnprocessableEntity},
		{"unknown membership", func(fixture, *Membership) uuid.UUID { return uuid.New() }, `{"number": 7}`, http.StatusNotFound},
		{
			name: "number already taken",
			id: func(f fixture, m *Membership) uuid.UUID {
				f.join(t, f.home, f.seed.CreatePlayer(testdb.PlayerParams{}), new(int32(7)), "2025-08-01")
				return m.ID
			},
			body:       `{"number": 7}`,
			wantStatus: http.StatusConflict,
		},
		{
			name: "player already left",
			id: func(f fixture, m *Membership) uuid.UUID {
				if _, err := f.store.Leave(t.Context(), f.season.LeagueID, f.season.ID, f.home.ID, f.player.ID, day(t, "2025-12-31")); err != nil {
					t.Fatalf("Leave() error = %v", err)
				}
				return m.ID
			},
			body:       `{"number": 7}`,
			wantStatus: http.StatusNotFound,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := newFixture(t)
			m := f.join(t, f.home, f.player, new(int32(10)), "2025-08-01")
			path := fmt.Sprintf("%s/%s", f.squadPath(f.home), tt.id(f, m))

			rec := testhttp.Do(t, newTestRouter(), http.MethodPatch, path, tt.body)
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func TestLeaveSquad(t *testing.T) {
	f := newFixture(t)
	m := f.join(t, f.home, f.player, new(int32(10)), "2025-08-01")
	path := fmt.Sprintf("%s/%s/leave", f.squadPath(f.home), m.ID)

	rec := testhttp.Do(t, newTestRouter(), http.MethodPost, path, `{"left_on": "2025-12-31"}`)
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}
	if got := decode[membershipResponse](t, rec); got.ID != m.ID || got.LeftOn == nil || *got.LeftOn != "2025-12-31" {
		t.Errorf("membership = %+v, want %s closed on 2025-12-31", got, m.ID)
	}
}

func TestLeaveSquad_Errors(t *testing.T) {
	tests := []struct {
		name       string
		id         func(m *Membership) string
		body       string
		wantStatus int
	}{
		{"invalid membership id", func(*Membership) string { return "abc" }, `{"left_on": "2025-12-31"}`, http.StatusBadRequest},
		{"missing leaving date", func(m *Membership) string { return m.ID.String() }, `{}`, http.StatusUnprocessableEntity},
		{"unknown membership", func(*Membership) string { return uuid.NewString() }, `{"left_on": "2025-12-31"}`, http.StatusNotFound},
		{"leaving before joining", func(m *Membership) string { return m.ID.String() }, `{"left_on": "2025-08-31"}`, http.StatusUnprocessableEntity},
		{"leaving outside the season", func(m *Membership) string { return m.ID.String() }, `{"left_on": "2026-06-01"}`, http.StatusUnprocessableEntity},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := newFixture(t)
			m := f.join(t, f.home, f.player, nil, "2025-09-01")
			path := fmt.Sprintf("%s/%s/leave", f.squadPath(f.home), tt.id(m))

			rec := testhttp.Do(t, newTestRouter(), http.MethodPost, path, tt.body)
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func TestLeaveSquad_Twice(t *testing.T) {
	f := newFixture(t)
	router := newTestRouter()
	m := f.join(t, f.home, f.player, nil, "2025-08-01")
	path := fmt.Sprintf("%s/%s/leave", f.squadPath(f.home), m.ID)

	if rec := testhttp.Do(t, router, http.MethodPost, path, `{"left_on": "2025-12-31"}`); rec.Code != http.StatusOK {
		t.Fatalf("first leave: status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}
	if rec := testhttp.Do(t, router, http.MethodPost, path, `{"left_on": "2026-01-31"}`); rec.Code != http.StatusConflict {
		t.Errorf("second leave: status = %d, want %d, body = %s", rec.Code, http.StatusConflict, rec.Body)
	}
}

func transferBody(playerID, from, to uuid.UUID, on string) string {
	return fmt.Sprintf(`{"player_id": %q, "from_team_id": %q, "to_team_id": %q, "number": 9, "on": %q}`, playerID, from, to, on)
}

func TestTransfer(t *testing.T) {
	f := newFixture(t)
	router := newTestRouter()
	f.join(t, f.home, f.player, new(int32(10)), "2025-08-01")

	rec := testhttp.Do(t, router, http.MethodPost, f.transfersPath(), transferBody(f.player.ID, f.home.ID, f.away.ID, "2026-01-15"))
	if rec.Code != http.StatusCreated {
		t.Fatalf("status = %d, want %d, body = %s", rec.Code, http.StatusCreated, rec.Body)
	}
	if got := decode[membershipResponse](t, rec); got.TeamID != f.away.ID || got.JoinedOn != "2026-01-15" {
		t.Errorf("membership = %+v, want the player in the away team from 2026-01-15", got)
	}

	if members := f.list(t, f.home, false); len(members) != 0 {
		t.Errorf("former squad has %d active members, want 0", len(members))
	}
	if members := f.list(t, f.away, false); len(members) != 1 {
		t.Errorf("new squad has %d active members, want 1", len(members))
	}
}

func TestTransfer_Errors(t *testing.T) {
	tests := []struct {
		name       string
		body       func(f fixture) string
		wantStatus int
	}{
		{
			name:       "same team on both sides",
			body:       func(f fixture) string { return transferBody(f.player.ID, f.home.ID, f.home.ID, "2026-01-15") },
			wantStatus: http.StatusUnprocessableEntity,
		},
		{
			name:       "player is not in the former team",
			body:       func(f fixture) string { return transferBody(f.player.ID, f.away.ID, f.home.ID, "2026-01-15") },
			wantStatus: http.StatusConflict,
		},
		{
			name:       "former team not registered",
			body:       func(f fixture) string { return transferBody(f.player.ID, f.unregistered.ID, f.away.ID, "2026-01-15") },
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "new team not registered",
			body:       func(f fixture) string { return transferBody(f.player.ID, f.home.ID, f.unregistered.ID, "2026-01-15") },
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "outside the season",
			body:       func(f fixture) string { return transferBody(f.player.ID, f.home.ID, f.away.ID, "2026-06-01") },
			wantStatus: http.StatusUnprocessableEntity,
		},
		{
			name: "number taken in the new team",
			body: func(f fixture) string {
				f.join(t, f.away, f.seed.CreatePlayer(testdb.PlayerParams{}), new(int32(9)), "2025-08-01")
				return transferBody(f.player.ID, f.home.ID, f.away.ID, "2026-01-15")
			},
			wantStatus: http.StatusConflict,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := newFixture(t)
			f.join(t, f.home, f.player, new(int32(10)), "2025-08-01")

			rec := testhttp.Do(t, newTestRouter(), http.MethodPost, f.transfersPath(), tt.body(f))
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}

			active, err := f.store.Active(t.Context(), f.season.LeagueID, f.season.ID, f.player.ID)
			if err != nil || active.TeamID != f.home.ID {
				t.Errorf("active membership = %+v (error %v), want the player still in the home team", active, err)
			}
		})
	}
}
