//go:build integration

package squadmembership

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/google/uuid"

	"league-s/internal/db"
	"league-s/internal/testdb"
)

type fixture struct {
	store        *PostgresStore
	seed         *testdb.Seeder
	season       db.Season
	home, away   db.Team
	unregistered db.Team
	player       db.Player
}

func newFixture(t *testing.T) fixture {
	t.Helper()
	s := testdb.New(t, testPool)
	f := fixture{
		store:        NewPostgresStore(testPool),
		seed:         s,
		season:       s.CreateSeason(testdb.SeasonParams{}),
		home:         s.CreateTeam(testdb.TeamParams{}),
		away:         s.CreateTeam(testdb.TeamParams{}),
		unregistered: s.CreateTeam(testdb.TeamParams{}),
		player:       s.CreatePlayer(testdb.PlayerParams{}),
	}
	s.RegisterTeams(f.season, f.home, f.away)
	return f
}

func day(t *testing.T, v string) time.Time {
	t.Helper()
	d, err := time.Parse(time.DateOnly, v)
	if err != nil {
		t.Fatalf("invalid date %q: %v", v, err)
	}
	return d
}

func (f fixture) membership(t *testing.T, team db.Team, p db.Player, n *int32, joinedOn string) *Membership {
	t.Helper()
	return &Membership{
		LeagueID: f.season.LeagueID,
		SeasonID: f.season.ID,
		TeamID:   team.ID,
		PlayerID: p.ID,
		Number:   n,
		JoinedOn: day(t, joinedOn),
	}
}

func (f fixture) join(t *testing.T, team db.Team, p db.Player, n *int32, joinedOn string) *Membership {
	t.Helper()
	m, err := f.store.Join(t.Context(), f.membership(t, team, p, n, joinedOn))
	if err != nil {
		t.Fatalf("join %s %s to %q: %v", p.Firstname, p.Lastname, team.Name, err)
	}
	return m
}

func (f fixture) list(t *testing.T, team db.Team, includeHistory bool) []*Member {
	t.Helper()
	members, err := f.store.List(t.Context(), f.season.LeagueID, f.season.ID, team.ID, includeHistory)
	if err != nil {
		t.Fatalf("list squad of %q: %v", team.Name, err)
	}
	return members
}

func TestJoinThenList(t *testing.T) {
	f := newFixture(t)

	m := f.join(t, f.home, f.player, new(int32(10)), "2025-08-01")
	if m.ID == uuid.Nil {
		t.Error("membership id is nil, want the id generated by the database")
	}

	members := f.list(t, f.home, false)
	if len(members) != 1 {
		t.Fatalf("squad has %d members, want 1", len(members))
	}
	got := members[0]
	if got.ID != f.player.ID || got.Number == nil || *got.Number != 10 || got.LeftOn != nil {
		t.Errorf("member = %+v, want the player with number 10 and no leaving date", got)
	}
}

func TestJoin_WithoutNumber(t *testing.T) {
	f := newFixture(t)
	other := f.seed.CreatePlayer(testdb.PlayerParams{})

	f.join(t, f.home, f.player, nil, "2025-08-01")
	f.join(t, f.home, other, nil, "2025-08-01")

	if members := f.list(t, f.home, false); len(members) != 2 {
		t.Errorf("squad has %d members, want 2: several players can have no number", len(members))
	}
}

func TestJoin_Errors(t *testing.T) {
	tests := []struct {
		name    string
		prepare func(f fixture) *Membership
		wantErr JoinError
	}{
		{
			name: "unknown player",
			prepare: func(f fixture) *Membership {
				m := f.membership(t, f.home, f.player, nil, "2025-08-01")
				m.PlayerID = uuid.New()
				return m
			},
			wantErr: ErrJoinPlayerNotFound,
		},
		{
			name: "player of another league",
			prepare: func(f fixture) *Membership {
				other := f.seed.CreateLeague(testdb.LeagueParams{})
				p := f.seed.CreatePlayer(testdb.PlayerParams{League: &other})
				return f.membership(t, f.home, p, nil, "2025-08-01")
			},
			wantErr: ErrJoinPlayerNotFound,
		},
		{
			name: "team not registered in the season",
			prepare: func(f fixture) *Membership {
				return f.membership(t, f.unregistered, f.player, nil, "2025-08-01")
			},
			wantErr: ErrJoinTeamNotRegistered,
		},
		{
			name: "player already active in another team",
			prepare: func(f fixture) *Membership {
				f.join(t, f.away, f.player, nil, "2025-08-01")
				return f.membership(t, f.home, f.player, nil, "2025-09-01")
			},
			wantErr: ErrJoinPlayerAlreadyActive,
		},
		{
			name: "number already taken",
			prepare: func(f fixture) *Membership {
				f.join(t, f.home, f.seed.CreatePlayer(testdb.PlayerParams{}), new(int32(10)), "2025-08-01")
				return f.membership(t, f.home, f.player, new(int32(10)), "2025-08-01")
			},
			wantErr: ErrJoinNumberTaken,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := newFixture(t)
			_, err := f.store.Join(t.Context(), tt.prepare(f))
			if !errors.Is(err, tt.wantErr) {
				t.Errorf("Join() error = %v, want %v", err, tt.wantErr)
			}
		})
	}
}

func TestLeave(t *testing.T) {
	f := newFixture(t)
	f.join(t, f.home, f.player, new(int32(10)), "2025-08-01")

	m, err := f.store.Leave(t.Context(), f.season.LeagueID, f.season.ID, f.home.ID, f.player.ID, day(t, "2025-12-31"))
	if err != nil {
		t.Fatalf("Leave() error = %v", err)
	}
	if m.LeftOn == nil || !m.LeftOn.Equal(day(t, "2025-12-31")) {
		t.Errorf("left_on = %v, want 2025-12-31", m.LeftOn)
	}

	if members := f.list(t, f.home, false); len(members) != 0 {
		t.Errorf("active squad has %d members, want 0", len(members))
	}
	history := f.list(t, f.home, true)
	if len(history) != 1 || history[0].LeftOn == nil {
		t.Errorf("history = %+v, want the player with a leaving date", history)
	}
}

func TestLeave_FreesTheNumber(t *testing.T) {
	f := newFixture(t)
	f.join(t, f.home, f.player, new(int32(10)), "2025-08-01")
	if _, err := f.store.Leave(t.Context(), f.season.LeagueID, f.season.ID, f.home.ID, f.player.ID, day(t, "2025-12-31")); err != nil {
		t.Fatalf("Leave() error = %v", err)
	}

	f.join(t, f.home, f.seed.CreatePlayer(testdb.PlayerParams{}), new(int32(10)), "2026-01-01")
}

func TestLeave_ThenComeBack(t *testing.T) {
	f := newFixture(t)
	f.join(t, f.home, f.player, new(int32(10)), "2025-08-01")
	if _, err := f.store.Leave(t.Context(), f.season.LeagueID, f.season.ID, f.home.ID, f.player.ID, day(t, "2025-10-31")); err != nil {
		t.Fatalf("Leave() error = %v", err)
	}
	f.join(t, f.home, f.player, new(int32(7)), "2026-02-01")

	history := f.list(t, f.home, true)
	if len(history) != 2 {
		t.Fatalf("history has %d stints, want 2", len(history))
	}
	if history[0].LeftOn == nil || history[1].LeftOn != nil {
		t.Errorf("history = %+v, want the first stint closed and the second one active", history)
	}
}

func TestLeave_Errors(t *testing.T) {
	tests := []struct {
		name    string
		prepare func(f fixture)
		leftOn  string
		wantErr LeaveError
	}{
		{
			name:    "never joined",
			prepare: func(fixture) {},
			leftOn:  "2025-12-31",
			wantErr: ErrLeaveNotActive,
		},
		{
			name: "already left",
			prepare: func(f fixture) {
				f.join(t, f.home, f.player, nil, "2025-08-01")
				if _, err := f.store.Leave(t.Context(), f.season.LeagueID, f.season.ID, f.home.ID, f.player.ID, day(t, "2025-10-31")); err != nil {
					t.Fatalf("first Leave() error = %v", err)
				}
			},
			leftOn:  "2025-12-31",
			wantErr: ErrLeaveNotActive,
		},
		{
			name:    "leaving before joining",
			prepare: func(f fixture) { f.join(t, f.home, f.player, nil, "2025-08-01") },
			leftOn:  "2025-07-31",
			wantErr: ErrLeaveBeforeJoining,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			f := newFixture(t)
			tt.prepare(f)
			_, err := f.store.Leave(t.Context(), f.season.LeagueID, f.season.ID, f.home.ID, f.player.ID, day(t, tt.leftOn))
			if !errors.Is(err, tt.wantErr) {
				t.Errorf("Leave() error = %v, want %v", err, tt.wantErr)
			}
		})
	}
}

func TestActive(t *testing.T) {
	f := newFixture(t)

	if _, err := f.store.Active(t.Context(), f.season.LeagueID, f.season.ID, f.player.ID); !errors.Is(err, ErrActiveNotFound) {
		t.Fatalf("Active() before joining: error = %v, want ErrActiveNotFound", err)
	}

	f.join(t, f.away, f.player, nil, "2025-08-01")
	m, err := f.store.Active(t.Context(), f.season.LeagueID, f.season.ID, f.player.ID)
	if err != nil {
		t.Fatalf("Active() error = %v", err)
	}
	if m.TeamID != f.away.ID {
		t.Errorf("active team = %s, want %s", m.TeamID, f.away.ID)
	}
}

func (f fixture) transfer(ctx context.Context, t *testing.T, to db.Team, n *int32, on string) error {
	t.Helper()
	tx, err := testPool.Begin(ctx)
	if err != nil {
		t.Fatalf("begin: %v", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	store := f.store.WithTx(tx)
	if _, err := store.Leave(ctx, f.season.LeagueID, f.season.ID, f.home.ID, f.player.ID, day(t, on)); err != nil {
		return err
	}
	if _, err := store.Join(ctx, f.membership(t, to, f.player, n, on)); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

func TestWithTx_Transfer(t *testing.T) {
	f := newFixture(t)
	f.join(t, f.home, f.player, new(int32(10)), "2025-08-01")

	if err := f.transfer(t.Context(), t, f.away, new(int32(9)), "2026-01-15"); err != nil {
		t.Fatalf("transfer: %v", err)
	}

	m, err := f.store.Active(t.Context(), f.season.LeagueID, f.season.ID, f.player.ID)
	if err != nil {
		t.Fatalf("Active() error = %v", err)
	}
	if m.TeamID != f.away.ID {
		t.Errorf("active team = %s, want %s", m.TeamID, f.away.ID)
	}
}

func TestWithTx_FailedTransferIsRolledBack(t *testing.T) {
	f := newFixture(t)
	f.join(t, f.home, f.player, new(int32(10)), "2025-08-01")
	f.join(t, f.away, f.seed.CreatePlayer(testdb.PlayerParams{}), new(int32(9)), "2025-08-01")

	err := f.transfer(t.Context(), t, f.away, new(int32(9)), "2026-01-15")
	if !errors.Is(err, ErrJoinNumberTaken) {
		t.Fatalf("transfer error = %v, want ErrJoinNumberTaken", err)
	}

	m, err := f.store.Active(t.Context(), f.season.LeagueID, f.season.ID, f.player.ID)
	if err != nil {
		t.Fatalf("Active() error = %v, want the player still in the first team", err)
	}
	if m.TeamID != f.home.ID || m.LeftOn != nil {
		t.Errorf("membership = %+v, want the player still active in the first team: the leave must be rolled back", m)
	}
}

func TestRules(t *testing.T) {
	f := newFixture(t)

	rules, err := f.store.Rules(t.Context(), f.season.LeagueID, f.season.ID, f.home.ID)
	if err != nil {
		t.Fatalf("Rules() error = %v", err)
	}
	if !rules.SeasonStartOn.Equal(f.season.StartOn) || !rules.SeasonEndOn.Equal(f.season.EndOn) || rules.MaxSize != nil {
		t.Errorf("rules = %+v, want the season dates and no max size", rules)
	}

	if _, err := f.store.Rules(t.Context(), f.season.LeagueID, f.season.ID, f.unregistered.ID); !errors.Is(err, ErrRulesTeamNotRegistered) {
		t.Errorf("Rules() on an unregistered team: error = %v, want ErrRulesTeamNotRegistered", err)
	}
}

func TestLockSquad(t *testing.T) {
	f := newFixture(t)

	rules, err := f.store.LockSquad(t.Context(), f.season.LeagueID, f.season.ID, f.home.ID)
	if err != nil {
		t.Fatalf("LockSquad() error = %v", err)
	}
	if !rules.SeasonStartOn.Equal(f.season.StartOn) || !rules.SeasonEndOn.Equal(f.season.EndOn) || rules.MaxSize != nil {
		t.Errorf("rules = %+v, want the season dates and no max size", rules)
	}

	if _, err := f.store.LockSquad(t.Context(), f.season.LeagueID, f.season.ID, f.unregistered.ID); !errors.Is(err, ErrLockTeamNotRegistered) {
		t.Errorf("LockSquad() on an unregistered team: error = %v, want ErrLockTeamNotRegistered", err)
	}
}

func TestLockSquad_BlocksASecondTransaction(t *testing.T) {
	f := newFixture(t)
	ctx := t.Context()

	first, err := testPool.Begin(ctx)
	if err != nil {
		t.Fatalf("begin: %v", err)
	}
	defer func() { _ = first.Rollback(ctx) }()
	if _, err := f.store.WithTx(first).LockSquad(ctx, f.season.LeagueID, f.season.ID, f.home.ID); err != nil {
		t.Fatalf("first LockSquad() error = %v", err)
	}

	second, err := testPool.Begin(ctx)
	if err != nil {
		t.Fatalf("begin: %v", err)
	}
	defer func() { _ = second.Rollback(ctx) }()

	waitCtx, cancel := context.WithTimeout(ctx, 200*time.Millisecond)
	defer cancel()
	if _, err := f.store.WithTx(second).LockSquad(waitCtx, f.season.LeagueID, f.season.ID, f.home.ID); err == nil {
		t.Fatal("second LockSquad() returned while the first transaction holds the lock, want it to wait")
	}
}

func TestCountActive(t *testing.T) {
	f := newFixture(t)
	f.join(t, f.home, f.player, nil, "2025-08-01")
	f.join(t, f.home, f.seed.CreatePlayer(testdb.PlayerParams{}), nil, "2025-08-01")
	if _, err := f.store.Leave(t.Context(), f.season.LeagueID, f.season.ID, f.home.ID, f.player.ID, day(t, "2025-12-31")); err != nil {
		t.Fatalf("Leave() error = %v", err)
	}

	n, err := f.store.CountActive(t.Context(), f.season.LeagueID, f.season.ID, f.home.ID)
	if err != nil {
		t.Fatalf("CountActive() error = %v", err)
	}
	if n != 1 {
		t.Errorf("CountActive() = %d, want 1: players who left are not counted", n)
	}
}
