//go:build integration

package team

import (
	"encoding/json"
	"fmt"
	"net/http"
	"slices"
	"strings"
	"testing"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"league-s/internal/db"
	"league-s/internal/testdb"
	"league-s/internal/testhttp"
)

func newTestRouter() http.Handler {
	r := chi.NewRouter()
	r.Mount("/api/v1/leagues/{leagueID}/teams", NewHandler(NewPostgresStore(testPool)).Routes())
	return r
}

func teamsPath(l db.League) string {
	return fmt.Sprintf("/api/v1/leagues/%s/teams", l.ID)
}

func TestCreateThenGetTeam(t *testing.T) {
	league := testdb.New(t, testPool).CreateLeague(testdb.LeagueParams{})
	router := newTestRouter()

	rec := testhttp.Do(t, router, http.MethodPost, teamsPath(league),
		`{"name": "Marseille", "logo": "https://example.com/om.png"}`)
	if rec.Code != http.StatusCreated {
		t.Fatalf("create: status = %d, want %d, body = %s", rec.Code, http.StatusCreated, rec.Body)
	}

	var created teamResponse
	if err := json.NewDecoder(rec.Body).Decode(&created); err != nil {
		t.Fatalf("decode create response: %v", err)
	}
	if created.ID == uuid.Nil {
		t.Fatal("create: id is 0, want the id generated by the database")
	}
	if created.LeagueID != league.ID {
		t.Errorf("create: league_id = %s, want %s (from the URL)", created.LeagueID, league.ID)
	}

	rec = testhttp.Do(t, router, http.MethodGet, fmt.Sprintf("%s/%s", teamsPath(league), created.ID), "")
	if rec.Code != http.StatusOK {
		t.Fatalf("get: status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}

	var got teamResponse
	if err := json.NewDecoder(rec.Body).Decode(&got); err != nil {
		t.Fatalf("decode get response: %v", err)
	}
	if got.Name != "Marseille" || got.Logo == nil || *got.Logo != "https://example.com/om.png" {
		t.Errorf("get: got %+v, want name Marseille with its logo", got)
	}
}

func TestCreateTeam_SameNameInAnotherLeague(t *testing.T) {
	s := testdb.New(t, testPool)
	s.CreateTeam(testdb.TeamParams{Name: "Les Bleus"})
	other := s.CreateLeague(testdb.LeagueParams{})

	rec := testhttp.Do(t, newTestRouter(), http.MethodPost, teamsPath(other), `{"name": "Les Bleus"}`)
	if rec.Code != http.StatusCreated {
		t.Errorf("status = %d, want %d: names are unique per league only, body = %s", rec.Code, http.StatusCreated, rec.Body)
	}
}

func TestCreateTeam_Errors(t *testing.T) {
	tests := []struct {
		name       string
		path       func(l db.League) string
		body       string
		wantStatus int
	}{
		{"invalid JSON", teamsPath, `{"name":`, http.StatusBadRequest},
		{"missing name", teamsPath, `{}`, http.StatusUnprocessableEntity},
		{"name too long", teamsPath, `{"name": "` + strings.Repeat("a", 51) + `"}`, http.StatusUnprocessableEntity},
		{"logo is not a URL", teamsPath, `{"name": "Lyon", "logo": "not a url"}`, http.StatusUnprocessableEntity},
		{"logo is not an http URL", teamsPath, `{"name": "Lyon", "logo": "javascript:alert(1)"}`, http.StatusUnprocessableEntity},
		{"name taken in the league", teamsPath, `{"name": "Les Bleus"}`, http.StatusConflict},
		{"unknown league", func(db.League) string { return "/api/v1/leagues/" + uuid.NewString() + "/teams" }, `{"name": "Lyon"}`, http.StatusNotFound},
		{"invalid league id", func(db.League) string { return "/api/v1/leagues/abc/teams" }, `{"name": "Lyon"}`, http.StatusBadRequest},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := testdb.New(t, testPool)
			league := s.CreateLeague(testdb.LeagueParams{})
			s.CreateTeam(testdb.TeamParams{League: &league, Name: "Les Bleus"})

			rec := testhttp.Do(t, newTestRouter(), http.MethodPost, tt.path(league), tt.body)
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func TestGetTeam_Errors(t *testing.T) {
	type fixture struct {
		league, other db.League
		team          db.Team
	}
	tests := []struct {
		name       string
		path       func(f fixture) string
		wantStatus int
	}{
		{
			name:       "unknown id",
			path:       func(f fixture) string { return teamsPath(f.league) + "/" + uuid.NewString() },
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "team of another league",
			path:       func(f fixture) string { return fmt.Sprintf("%s/%s", teamsPath(f.other), f.team.ID) },
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "invalid id",
			path:       func(f fixture) string { return teamsPath(f.league) + "/abc" },
			wantStatus: http.StatusBadRequest,
		},
		{
			name:       "invalid league id",
			path:       func(f fixture) string { return fmt.Sprintf("/api/v1/leagues/abc/teams/%s", f.team.ID) },
			wantStatus: http.StatusBadRequest,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := testdb.New(t, testPool)
			f := fixture{league: s.CreateLeague(testdb.LeagueParams{}), other: s.CreateLeague(testdb.LeagueParams{})}
			f.team = s.CreateTeam(testdb.TeamParams{League: &f.league})

			rec := testhttp.Do(t, newTestRouter(), http.MethodGet, tt.path(f), "")
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}

func TestListTeams(t *testing.T) {
	s := testdb.New(t, testPool)
	league := s.CreateLeague(testdb.LeagueParams{})
	other := s.CreateLeague(testdb.LeagueParams{})
	s.CreateTeam(testdb.TeamParams{League: &league, Name: "Lyon"})
	s.CreateTeam(testdb.TeamParams{League: &league, Name: "Lens"})
	s.CreateTeam(testdb.TeamParams{League: &other, Name: "Nantes"})

	rec := testhttp.Do(t, newTestRouter(), http.MethodGet, teamsPath(league), "")
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}

	var got []teamResponse
	if err := json.NewDecoder(rec.Body).Decode(&got); err != nil {
		t.Fatalf("decode response: %v, body = %s", err, rec.Body)
	}

	var names []string
	for _, team := range got {
		names = append(names, team.Name)
		if team.LeagueID != league.ID {
			t.Errorf("team %q has league_id %s, want %s", team.Name, team.LeagueID, league.ID)
		}
	}
	if !slices.Equal(names, []string{"Lens", "Lyon"}) {
		t.Errorf("teams = %v, want [Lens Lyon]: teams of the league only, sorted by name", names)
	}
}

func TestListTeams_Empty(t *testing.T) {
	s := testdb.New(t, testPool)
	s.CreateTeam(testdb.TeamParams{})
	empty := s.CreateLeague(testdb.LeagueParams{})

	rec := testhttp.Do(t, newTestRouter(), http.MethodGet, teamsPath(empty), "")
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want %d, body = %s", rec.Code, http.StatusOK, rec.Body)
	}
	if body := strings.TrimSpace(rec.Body.String()); body != "[]" {
		t.Errorf("body = %s, want []", body)
	}
}

func TestListTeams_Errors(t *testing.T) {
	tests := []struct {
		name       string
		path       string
		wantStatus int
		skip       string
	}{
		{"invalid league id", "/api/v1/leagues/abc/teams", http.StatusBadRequest, ""},
		{"unknown league", "/api/v1/leagues/" + uuid.NewString() + "/teams", http.StatusNotFound, "league existence is not checked yet, see the TODO in team.Handler.list"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if tt.skip != "" {
				t.Skip(tt.skip)
			}
			testdb.New(t, testPool)

			rec := testhttp.Do(t, newTestRouter(), http.MethodGet, tt.path, "")
			if rec.Code != tt.wantStatus {
				t.Errorf("status = %d, want %d, body = %s", rec.Code, tt.wantStatus, rec.Body)
			}
		})
	}
}
