// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: league.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createLeague = `-- name: CreateLeague :one
INSERT INTO league (name, logo)
VALUES ($1, $2)
RETURNING id, name, logo, created_at, updated_at
`

type CreateLeagueParams struct {
	Name string
	Logo *string
}

func (q *Queries) CreateLeague(ctx context.Context, arg CreateLeagueParams) (League, error) {
	row := q.db.QueryRow(ctx, createLeague, arg.Name, arg.Logo)
	var i League
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Logo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLeague = `-- name: DeleteLeague :one
DELETE FROM league WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteLeague(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteLeague, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getLeagueByID = `-- name: GetLeagueByID :one
SELECT id, name, logo, created_at, updated_at FROM league WHERE id = $1
`

func (q *Queries) GetLeagueByID(ctx context.Context, id uuid.UUID) (League, error) {
	row := q.db.QueryRow(ctx, getLeagueByID, id)
	var i League
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Logo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeagues = `-- name: GetLeagues :many
SELECT id, name, logo, created_at, updated_at FROM league ORDER BY name
`

func (q *Queries) GetLeagues(ctx context.Context) ([]League, error) {
	rows, err := q.db.Query(ctx, getLeagues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []League
	for rows.Next() {
		var i League
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Logo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
