// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTeamMatchesOnMatchday = `-- name: CountTeamMatchesOnMatchday :one
SELECT count(*) FROM match
WHERE season_id = $1
  AND matchday = $2
  AND status <> 'cancelled'
  AND id <> $3
  AND (home_team_id = ANY($4::uuid[]) OR away_team_id = ANY($4::uuid[]))
`

type CountTeamMatchesOnMatchdayParams struct {
	SeasonID  uuid.UUID
	Matchday  int32
	ExcludeID uuid.UUID
	TeamIds   []uuid.UUID
}

func (q *Queries) CountTeamMatchesOnMatchday(ctx context.Context, arg CountTeamMatchesOnMatchdayParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamMatchesOnMatchday,
		arg.SeasonID,
		arg.Matchday,
		arg.ExcludeID,
		arg.TeamIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO match (season_id, home_team_id, away_team_id, matchday, kickoff_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, season_id, home_team_id, away_team_id, matchday, kickoff_at, status, home_score, away_score, created_at, updated_at
`

type CreateMatchParams struct {
	SeasonID   uuid.UUID
	HomeTeamID uuid.UUID
	AwayTeamID uuid.UUID
	Matchday   int32
	KickoffAt  *time.Time
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.SeasonID,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.Matchday,
		arg.KickoffAt,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.Matchday,
		&i.KickoffAt,
		&i.Status,
		&i.HomeScore,
		&i.AwayScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMatch = `-- name: DeleteMatch :execrows
DELETE FROM match
USING season
WHERE match.id = $1
  AND match.season_id = $2
  AND season.id = match.season_id
  AND season.league_id = $3
`

type DeleteMatchParams struct {
	ID       uuid.UUID
	SeasonID uuid.UUID
	LeagueID uuid.UUID
}

func (q *Queries) DeleteMatch(ctx context.Context, arg DeleteMatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMatch, arg.ID, arg.SeasonID, arg.LeagueID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMatch = `-- name: GetMatch :one
SELECT match.id, match.season_id, match.home_team_id, match.away_team_id, match.matchday, match.kickoff_at, match.status, match.home_score, match.away_score, match.created_at, match.updated_at FROM match
JOIN season ON season.id = match.season_id
WHERE match.id = $1
  AND match.season_id = $2
  AND season.league_id = $3
`

type GetMatchParams struct {
	ID       uuid.UUID
	SeasonID uuid.UUID
	LeagueID uuid.UUID
}

func (q *Queries) GetMatch(ctx context.Context, arg GetMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, getMatch, arg.ID, arg.SeasonID, arg.LeagueID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.Matchday,
		&i.KickoffAt,
		&i.Status,
		&i.HomeScore,
		&i.AwayScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatchForUpdate = `-- name: GetMatchForUpdate :one
SELECT match.id, match.season_id, match.home_team_id, match.away_team_id, match.matchday, match.kickoff_at, match.status, match.home_score, match.away_score, match.created_at, match.updated_at FROM match
JOIN season ON season.id = match.season_id
WHERE match.id = $1
  AND match.season_id = $2
  AND season.league_id = $3
FOR UPDATE OF match
`

type GetMatchForUpdateParams struct {
	ID       uuid.UUID
	SeasonID uuid.UUID
	LeagueID uuid.UUID
}

func (q *Queries) GetMatchForUpdate(ctx context.Context, arg GetMatchForUpdateParams) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchForUpdate, arg.ID, arg.SeasonID, arg.LeagueID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.Matchday,
		&i.KickoffAt,
		&i.Status,
		&i.HomeScore,
		&i.AwayScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMatches = `-- name: ListMatches :many
SELECT match.id, match.season_id, match.home_team_id, match.away_team_id, match.matchday, match.kickoff_at, match.status, match.home_score, match.away_score, match.created_at, match.updated_at FROM match
JOIN season ON season.id = match.season_id
WHERE match.season_id = $1
  AND season.league_id = $2
  AND ($3::int IS NULL OR match.matchday = $3::int)
  AND ($4::timestamptz IS NULL OR match.kickoff_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR match.kickoff_at < $5::timestamptz)
  AND ($6::uuid IS NULL OR $6::uuid IN (match.home_team_id, match.away_team_id))
  AND ($7::match_status IS NULL OR match.status = $7::match_status)
ORDER BY match.matchday, match.kickoff_at NULLS LAST, match.id
`

type ListMatchesParams struct {
	SeasonID uuid.UUID
	LeagueID uuid.UUID
	Matchday *int32
	FromAt   *time.Time
	ToAt     *time.Time
	TeamID   pgtype.UUID
	Status   *MatchStatus
}

func (q *Queries) ListMatches(ctx context.Context, arg ListMatchesParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatches,
		arg.SeasonID,
		arg.LeagueID,
		arg.Matchday,
		arg.FromAt,
		arg.ToAt,
		arg.TeamID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.Matchday,
			&i.KickoffAt,
			&i.Status,
			&i.HomeScore,
			&i.AwayScore,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSeason = `-- name: LockSeason :one
SELECT start_on, end_on FROM season
WHERE id = $1 AND league_id = $2
FOR UPDATE
`

type LockSeasonParams struct {
	ID       uuid.UUID
	LeagueID uuid.UUID
}

type LockSeasonRow struct {
	StartOn time.Time
	EndOn   time.Time
}

func (q *Queries) LockSeason(ctx context.Context, arg LockSeasonParams) (LockSeasonRow, error) {
	row := q.db.QueryRow(ctx, lockSeason, arg.ID, arg.LeagueID)
	var i LockSeasonRow
	err := row.Scan(&i.StartOn, &i.EndOn)
	return i, err
}

const updateMatch = `-- name: UpdateMatch :one
UPDATE match
SET matchday = $1,
    kickoff_at = $2,
    status = $3,
    home_score = $4,
    away_score = $5,
    updated_at = now()
FROM season
WHERE match.id = $6
  AND match.season_id = $7
  AND season.id = match.season_id
  AND season.league_id = $8
RETURNING match.id, match.season_id, match.home_team_id, match.away_team_id, match.matchday, match.kickoff_at, match.status, match.home_score, match.away_score, match.created_at, match.updated_at
`

type UpdateMatchParams struct {
	Matchday  int32
	KickoffAt *time.Time
	Status    MatchStatus
	HomeScore *int32
	AwayScore *int32
	ID        uuid.UUID
	SeasonID  uuid.UUID
	LeagueID  uuid.UUID
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatch,
		arg.Matchday,
		arg.KickoffAt,
		arg.Status,
		arg.HomeScore,
		arg.AwayScore,
		arg.ID,
		arg.SeasonID,
		arg.LeagueID,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.Matchday,
		&i.KickoffAt,
		&i.Status,
		&i.HomeScore,
		&i.AwayScore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
