// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type MatchStatus string

const (
	MatchStatusScheduled MatchStatus = "scheduled"
	MatchStatusLive      MatchStatus = "live"
	MatchStatusFinished  MatchStatus = "finished"
	MatchStatusPostponed MatchStatus = "postponed"
	MatchStatusCancelled MatchStatus = "cancelled"
)

func (e *MatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchStatus(s)
	case string:
		*e = MatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchStatus: %T", src)
	}
	return nil
}

type NullMatchStatus struct {
	MatchStatus MatchStatus
	Valid       bool // Valid is true if MatchStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MatchStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchStatus), nil
}

type League struct {
	ID        uuid.UUID
	Name      string
	Logo      *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Match struct {
	ID            uuid.UUID
	SeasonID      uuid.UUID
	HomeTeamID    uuid.UUID
	AwayTeamID    uuid.UUID
	Matchday      int32
	KickoffAt     *time.Time
	Status        MatchStatus
	HomeScore     *int32
	AwayScore     *int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Venue         *string
	Referee       *string
	ConvocationAt *time.Time
	VideoUrl      *string
}

type Player struct {
	ID        uuid.UUID
	LeagueID  uuid.UUID
	Firstname string
	Lastname  string
	Icon      *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Season struct {
	ID           uuid.UUID
	Name         string
	StartOn      time.Time
	EndOn        time.Time
	MatchWinPts  int32
	MatchDrawPts int32
	MatchLossPts int32
	TieBreakers  []string
	MaxSquadSize *int32
	LeagueID     uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type SeasonTeam struct {
	SeasonID  uuid.UUID
	TeamID    uuid.UUID
	LeagueID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SquadMembership struct {
	ID        uuid.UUID
	PlayerID  uuid.UUID
	SeasonID  uuid.UUID
	TeamID    uuid.UUID
	LeagueID  uuid.UUID
	Number    *int32
	JoinedOn  time.Time
	LeftOn    *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Team struct {
	ID        uuid.UUID
	LeagueID  uuid.UUID
	Name      string
	Logo      *string
	CreatedAt time.Time
	UpdatedAt time.Time
}
