// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MatchStatus string

const (
	MatchStatusScheduled MatchStatus = "scheduled"
	MatchStatusLive      MatchStatus = "live"
	MatchStatusFinished  MatchStatus = "finished"
	MatchStatusPostponed MatchStatus = "postponed"
	MatchStatusCancelled MatchStatus = "cancelled"
)

func (e *MatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchStatus(s)
	case string:
		*e = MatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchStatus: %T", src)
	}
	return nil
}

type NullMatchStatus struct {
	MatchStatus MatchStatus
	Valid       bool // Valid is true if MatchStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MatchStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchStatus), nil
}

type League struct {
	ID        int64
	Name      string
	Logo      *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Match struct {
	ID         int64
	SeasonID   int64
	HomeTeamID int64
	AwayTeamID int64
	Matchday   int32
	KickoffAt  pgtype.Timestamptz
	Status     MatchStatus
	HomeScore  *int32
	AwayScore  *int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Player struct {
	ID        int64
	Firstname string
	Lastname  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Season struct {
	ID           int64
	Name         string
	StartOn      pgtype.Date
	EndOn        pgtype.Date
	MatchWinPts  int32
	MatchDrawPts int32
	MatchLossPts int32
	TieBreakers  []string
	LeagueID     int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type SeasonTeam struct {
	SeasonID  int64
	TeamID    int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Team struct {
	ID        int64
	Name      string
	Logo      *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TeamMembership struct {
	ID        int64
	PlayerID  int64
	SeasonID  int64
	TeamID    int64
	Number    *int32
	JoinedOn  pgtype.Date
	LeftOn    pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
