// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO player (league_id, firstname, lastname, icon)
VALUES ($1, $2, $3, $4)
RETURNING id, league_id, firstname, lastname, icon, created_at, updated_at
`

type CreatePlayerParams struct {
	LeagueID  uuid.UUID
	Firstname string
	Lastname  string
	Icon      *string
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer,
		arg.LeagueID,
		arg.Firstname,
		arg.Lastname,
		arg.Icon,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.Firstname,
		&i.Lastname,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, league_id, firstname, lastname, icon, created_at, updated_at FROM player WHERE id = $1 AND league_id = $2
`

type GetPlayerByIDParams struct {
	ID       uuid.UUID
	LeagueID uuid.UUID
}

func (q *Queries) GetPlayerByID(ctx context.Context, arg GetPlayerByIDParams) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, arg.ID, arg.LeagueID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.Firstname,
		&i.Lastname,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayer = `-- name: UpdatePlayer :one
UPDATE player
SET firstname = $1, lastname = $2, updated_at = now()
WHERE id = $3 AND league_id = $4
RETURNING id, league_id, firstname, lastname, icon, created_at, updated_at
`

type UpdatePlayerParams struct {
	Firstname string
	Lastname  string
	ID        uuid.UUID
	LeagueID  uuid.UUID
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayer,
		arg.Firstname,
		arg.Lastname,
		arg.ID,
		arg.LeagueID,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.Firstname,
		&i.Lastname,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
