// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: season_team.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTeamToSeason = `-- name: AddTeamToSeason :one
INSERT INTO season_team (season_id, team_id, league_id)
VALUES ($1, $2, $3)
RETURNING season_id, team_id, league_id, created_at, updated_at
`

type AddTeamToSeasonParams struct {
	SeasonID uuid.UUID
	TeamID   uuid.UUID
	LeagueID uuid.UUID
}

func (q *Queries) AddTeamToSeason(ctx context.Context, arg AddTeamToSeasonParams) (SeasonTeam, error) {
	row := q.db.QueryRow(ctx, addTeamToSeason, arg.SeasonID, arg.TeamID, arg.LeagueID)
	var i SeasonTeam
	err := row.Scan(
		&i.SeasonID,
		&i.TeamID,
		&i.LeagueID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamsBySeason = `-- name: GetTeamsBySeason :many
SELECT team.id, team.league_id, team.name, team.logo, team.created_at, team.updated_at FROM team
JOIN season_team ON season_team.team_id = team.id
WHERE season_team.season_id = $1
  AND season_team.league_id = $2
ORDER BY team.name
`

type GetTeamsBySeasonParams struct {
	SeasonID uuid.UUID
	LeagueID uuid.UUID
}

func (q *Queries) GetTeamsBySeason(ctx context.Context, arg GetTeamsBySeasonParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, getTeamsBySeason, arg.SeasonID, arg.LeagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.Name,
			&i.Logo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamFromSeason = `-- name: RemoveTeamFromSeason :one
DELETE FROM season_team
WHERE season_id = $1 AND team_id = $2 AND league_id = $3
RETURNING season_id, team_id, league_id, created_at, updated_at
`

type RemoveTeamFromSeasonParams struct {
	SeasonID uuid.UUID
	TeamID   uuid.UUID
	LeagueID uuid.UUID
}

func (q *Queries) RemoveTeamFromSeason(ctx context.Context, arg RemoveTeamFromSeasonParams) (SeasonTeam, error) {
	row := q.db.QueryRow(ctx, removeTeamFromSeason, arg.SeasonID, arg.TeamID, arg.LeagueID)
	var i SeasonTeam
	err := row.Scan(
		&i.SeasonID,
		&i.TeamID,
		&i.LeagueID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
