// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: season.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSeason = `-- name: CreateSeason :one
INSERT INTO season (
    name, start_on, end_on, match_win_pts, match_draw_pts, match_loss_pts, tie_breakers, league_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, name, start_on, end_on, match_win_pts, match_draw_pts, match_loss_pts, tie_breakers, max_squad_size, league_id, created_at, updated_at
`

type CreateSeasonParams struct {
	Name         string
	StartOn      time.Time
	EndOn        time.Time
	MatchWinPts  int32
	MatchDrawPts int32
	MatchLossPts int32
	TieBreakers  []string
	LeagueID     uuid.UUID
}

func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, createSeason,
		arg.Name,
		arg.StartOn,
		arg.EndOn,
		arg.MatchWinPts,
		arg.MatchDrawPts,
		arg.MatchLossPts,
		arg.TieBreakers,
		arg.LeagueID,
	)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartOn,
		&i.EndOn,
		&i.MatchWinPts,
		&i.MatchDrawPts,
		&i.MatchLossPts,
		&i.TieBreakers,
		&i.MaxSquadSize,
		&i.LeagueID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeasonByID = `-- name: GetSeasonByID :one
SELECT id, name, start_on, end_on, match_win_pts, match_draw_pts, match_loss_pts, tie_breakers, max_squad_size, league_id, created_at, updated_at FROM season WHERE id = $1 AND league_id = $2
`

type GetSeasonByIDParams struct {
	ID       uuid.UUID
	LeagueID uuid.UUID
}

func (q *Queries) GetSeasonByID(ctx context.Context, arg GetSeasonByIDParams) (Season, error) {
	row := q.db.QueryRow(ctx, getSeasonByID, arg.ID, arg.LeagueID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartOn,
		&i.EndOn,
		&i.MatchWinPts,
		&i.MatchDrawPts,
		&i.MatchLossPts,
		&i.TieBreakers,
		&i.MaxSquadSize,
		&i.LeagueID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeasonsByLeague = `-- name: GetSeasonsByLeague :many
SELECT id, name, start_on, end_on, match_win_pts, match_draw_pts, match_loss_pts, tie_breakers, max_squad_size, league_id, created_at, updated_at FROM season WHERE league_id = $1 ORDER BY start_on DESC
`

func (q *Queries) GetSeasonsByLeague(ctx context.Context, leagueID uuid.UUID) ([]Season, error) {
	rows, err := q.db.Query(ctx, getSeasonsByLeague, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Season
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartOn,
			&i.EndOn,
			&i.MatchWinPts,
			&i.MatchDrawPts,
			&i.MatchLossPts,
			&i.TieBreakers,
			&i.MaxSquadSize,
			&i.LeagueID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
