// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: squad_membership.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeSquadMembership = `-- name: CloseSquadMembership :one
UPDATE squad_membership
SET left_on = $1::date, updated_at = now()
WHERE player_id = $2
  AND season_id = $3
  AND team_id = $4
  AND league_id = $5
  AND left_on IS NULL
RETURNING id, player_id, season_id, team_id, league_id, number, joined_on, left_on, created_at, updated_at
`

type CloseSquadMembershipParams struct {
	LeftOn   time.Time
	PlayerID uuid.UUID
	SeasonID uuid.UUID
	TeamID   uuid.UUID
	LeagueID uuid.UUID
}

func (q *Queries) CloseSquadMembership(ctx context.Context, arg CloseSquadMembershipParams) (SquadMembership, error) {
	row := q.db.QueryRow(ctx, closeSquadMembership,
		arg.LeftOn,
		arg.PlayerID,
		arg.SeasonID,
		arg.TeamID,
		arg.LeagueID,
	)
	var i SquadMembership
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.SeasonID,
		&i.TeamID,
		&i.LeagueID,
		&i.Number,
		&i.JoinedOn,
		&i.LeftOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveSquadMembers = `-- name: CountActiveSquadMembers :one
SELECT count(*) FROM squad_membership
WHERE season_id = $1
  AND team_id = $2
  AND league_id = $3
  AND left_on IS NULL
`

type CountActiveSquadMembersParams struct {
	SeasonID uuid.UUID
	TeamID   uuid.UUID
	LeagueID uuid.UUID
}

func (q *Queries) CountActiveSquadMembers(ctx context.Context, arg CountActiveSquadMembersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSquadMembers, arg.SeasonID, arg.TeamID, arg.LeagueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSquadMembership = `-- name: CreateSquadMembership :one
INSERT INTO squad_membership (player_id, season_id, team_id, league_id, number, joined_on)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, player_id, season_id, team_id, league_id, number, joined_on, left_on, created_at, updated_at
`

type CreateSquadMembershipParams struct {
	PlayerID uuid.UUID
	SeasonID uuid.UUID
	TeamID   uuid.UUID
	LeagueID uuid.UUID
	Number   *int32
	JoinedOn time.Time
}

func (q *Queries) CreateSquadMembership(ctx context.Context, arg CreateSquadMembershipParams) (SquadMembership, error) {
	row := q.db.QueryRow(ctx, createSquadMembership,
		arg.PlayerID,
		arg.SeasonID,
		arg.TeamID,
		arg.LeagueID,
		arg.Number,
		arg.JoinedOn,
	)
	var i SquadMembership
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.SeasonID,
		&i.TeamID,
		&i.LeagueID,
		&i.Number,
		&i.JoinedOn,
		&i.LeftOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSquadMembership = `-- name: GetActiveSquadMembership :one
SELECT id, player_id, season_id, team_id, league_id, number, joined_on, left_on, created_at, updated_at FROM squad_membership
WHERE player_id = $1
  AND season_id = $2
  AND league_id = $3
  AND left_on IS NULL
`

type GetActiveSquadMembershipParams struct {
	PlayerID uuid.UUID
	SeasonID uuid.UUID
	LeagueID uuid.UUID
}

func (q *Queries) GetActiveSquadMembership(ctx context.Context, arg GetActiveSquadMembershipParams) (SquadMembership, error) {
	row := q.db.QueryRow(ctx, getActiveSquadMembership, arg.PlayerID, arg.SeasonID, arg.LeagueID)
	var i SquadMembership
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.SeasonID,
		&i.TeamID,
		&i.LeagueID,
		&i.Number,
		&i.JoinedOn,
		&i.LeftOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSquadMembership = `-- name: GetSquadMembership :one
SELECT id, player_id, season_id, team_id, league_id, number, joined_on, left_on, created_at, updated_at FROM squad_membership
WHERE id = $1
  AND season_id = $2
  AND team_id = $3
  AND league_id = $4
`

type GetSquadMembershipParams struct {
	ID       uuid.UUID
	SeasonID uuid.UUID
	TeamID   uuid.UUID
	LeagueID uuid.UUID
}

func (q *Queries) GetSquadMembership(ctx context.Context, arg GetSquadMembershipParams) (SquadMembership, error) {
	row := q.db.QueryRow(ctx, getSquadMembership,
		arg.ID,
		arg.SeasonID,
		arg.TeamID,
		arg.LeagueID,
	)
	var i SquadMembership
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.SeasonID,
		&i.TeamID,
		&i.LeagueID,
		&i.Number,
		&i.JoinedOn,
		&i.LeftOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSquadRules = `-- name: GetSquadRules :one
SELECT season.start_on, season.end_on, season.max_squad_size
FROM season_team
JOIN season ON season.id = season_team.season_id
  AND season.league_id = season_team.league_id
WHERE season_team.season_id = $1
  AND season_team.team_id = $2
  AND season_team.league_id = $3
`

type GetSquadRulesParams struct {
	SeasonID uuid.UUID
	TeamID   uuid.UUID
	LeagueID uuid.UUID
}

type GetSquadRulesRow struct {
	StartOn      time.Time
	EndOn        time.Time
	MaxSquadSize *int32
}

func (q *Queries) GetSquadRules(ctx context.Context, arg GetSquadRulesParams) (GetSquadRulesRow, error) {
	row := q.db.QueryRow(ctx, getSquadRules, arg.SeasonID, arg.TeamID, arg.LeagueID)
	var i GetSquadRulesRow
	err := row.Scan(&i.StartOn, &i.EndOn, &i.MaxSquadSize)
	return i, err
}

const listSquadMemberships = `-- name: ListSquadMemberships :many
SELECT player.id, player.league_id, player.firstname, player.lastname, player.icon, player.created_at, player.updated_at, squad_membership.id AS membership_id, squad_membership.number, squad_membership.joined_on, squad_membership.left_on
FROM squad_membership
JOIN player ON player.id = squad_membership.player_id
  AND player.league_id = squad_membership.league_id
WHERE squad_membership.season_id = $1
  AND squad_membership.team_id = $2
  AND squad_membership.league_id = $3
  AND ($4::boolean OR squad_membership.left_on IS NULL)
ORDER BY player.lastname, player.firstname, squad_membership.joined_on
`

type ListSquadMembershipsParams struct {
	SeasonID       uuid.UUID
	TeamID         uuid.UUID
	LeagueID       uuid.UUID
	IncludeHistory bool
}

type ListSquadMembershipsRow struct {
	Player       Player
	MembershipID uuid.UUID
	Number       *int32
	JoinedOn     time.Time
	LeftOn       *time.Time
}

func (q *Queries) ListSquadMemberships(ctx context.Context, arg ListSquadMembershipsParams) ([]ListSquadMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listSquadMemberships,
		arg.SeasonID,
		arg.TeamID,
		arg.LeagueID,
		arg.IncludeHistory,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSquadMembershipsRow
	for rows.Next() {
		var i ListSquadMembershipsRow
		if err := rows.Scan(
			&i.Player.ID,
			&i.Player.LeagueID,
			&i.Player.Firstname,
			&i.Player.Lastname,
			&i.Player.Icon,
			&i.Player.CreatedAt,
			&i.Player.UpdatedAt,
			&i.MembershipID,
			&i.Number,
			&i.JoinedOn,
			&i.LeftOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSquad = `-- name: LockSquad :one
SELECT season.start_on, season.end_on, season.max_squad_size
FROM season_team
JOIN season ON season.id = season_team.season_id
  AND season.league_id = season_team.league_id
WHERE season_team.season_id = $1
  AND season_team.team_id = $2
  AND season_team.league_id = $3
FOR UPDATE OF season_team
`

type LockSquadParams struct {
	SeasonID uuid.UUID
	TeamID   uuid.UUID
	LeagueID uuid.UUID
}

type LockSquadRow struct {
	StartOn      time.Time
	EndOn        time.Time
	MaxSquadSize *int32
}

func (q *Queries) LockSquad(ctx context.Context, arg LockSquadParams) (LockSquadRow, error) {
	row := q.db.QueryRow(ctx, lockSquad, arg.SeasonID, arg.TeamID, arg.LeagueID)
	var i LockSquadRow
	err := row.Scan(&i.StartOn, &i.EndOn, &i.MaxSquadSize)
	return i, err
}

const updateSquadMembershipNumber = `-- name: UpdateSquadMembershipNumber :one
UPDATE squad_membership
SET number = $1, updated_at = now()
WHERE id = $2
  AND season_id = $3
  AND team_id = $4
  AND league_id = $5
  AND left_on IS NULL
RETURNING id, player_id, season_id, team_id, league_id, number, joined_on, left_on, created_at, updated_at
`

type UpdateSquadMembershipNumberParams struct {
	Number   *int32
	ID       uuid.UUID
	SeasonID uuid.UUID
	TeamID   uuid.UUID
	LeagueID uuid.UUID
}

func (q *Queries) UpdateSquadMembershipNumber(ctx context.Context, arg UpdateSquadMembershipNumberParams) (SquadMembership, error) {
	row := q.db.QueryRow(ctx, updateSquadMembershipNumber,
		arg.Number,
		arg.ID,
		arg.SeasonID,
		arg.TeamID,
		arg.LeagueID,
	)
	var i SquadMembership
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.SeasonID,
		&i.TeamID,
		&i.LeagueID,
		&i.Number,
		&i.JoinedOn,
		&i.LeftOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
